### ISSUE TITLE
FlxTween.num calls TweenFunction twice with last value

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1869] opened 2016-06-16 11:23 UTC
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
windows/debug, maybe others

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.tweens.FlxTween;

class PlayState extends FlxState
{
	override public function create():Void 
	{	
		FlxTween.num(0, 1, 0.1, null, numCallback);
	}
	function numCallback(v:Float) {
		trace(v);
	}
}
```

________________________________

**Observed behavior:**
```
Running process: C:\HaxeToolkit\haxe\haxelib.exe run lime run "Project.xml" windows -debug
PlayState.hx:25: 0.166666666666667
PlayState.hx:25: 0.333333333333333
PlayState.hx:25: 0.5
PlayState.hx:25: 0.666666666666667
PlayState.hx:25: 0.833333333333333
PlayState.hx:25: 1
PlayState.hx:25: 1
Done(0)
```
**Expected behavior:**
only one `PlayState.hx:25: 1`

**Comment by MSGhero** [comment] 2016-07-02 21:17
```
TestState.hx:18: 0.16666666666666666
TestState.hx:18: 0.3333333333333333
TestState.hx:18: 0.5
TestState.hx:18: 0.6666666666666666
TestState.hx:18: 0.8333333333333333
TestState.hx:18: 0.9999999999999999
TestState.hx:18: 1
```
This is my output in flash.

**Comment by IBwWG** [comment] 2016-07-04 06:35
Aha, so not flash.  Were you seeing the same behaviour as I was on Windows or at least cpp?

**Comment by MSGhero** [comment] 2016-07-04 12:05
I only tested on flash, but I'm pretty sure your issue is just an issue with rounding or precision. Unless that happens for every choice of start, end, and duration numbers, you just got unlucky.

**Comment by IBwWG** [comment] 2016-07-04 12:32
Such unluck can cause problems, though.

**Comment by MSGhero** [comment] 2016-07-04 18:52
I mean... it's a hardware issue. I don't really see what flixel can do about that except for rounding the numbers, which is probably a bad idea. Your code should be able to handle it, regardless.

**Comment by azrafe7** [comment] 2016-07-04 19:37
It's a problem with the string representation (and its rounding), but the actual float value is correct, as you can see by running this:

```haxe
class PlayState extends FlxState
{
	var values:Array<Float> = [];
	
    override public function create():Void 
    {   
        FlxTween.num(0, 1, 0.1, { onComplete:onComplete } , numCallback);
    }
    
	function numCallback(v:Float) {
        trace(v);
		values.push(v);
    }
    
	function onComplete(tween) {
		function isOne(f:Float):String {
			return '$f == 1.0 ? ' + (f == 1.0 ? true : false);
		}
		
		Sys.println(values.map(isOne).join("\n"));
    }
}
```
which should give:
```
...
0.833333333333333 == 1.0 ? false
1 == 1.0 ? false  
1 == 1.0 ? true
```

**Comment by MSGhero** [comment] 2016-07-04 20:44
I think the problem is either attempting to `onComplete` via the update callback (which is why `onComplete` exists) or that now it takes 1.167 seconds to accomplish a 1 second tween.

**Comment by azrafe7** [comment] 2016-07-04 21:43
@MSGhero, I think we're on the same page here (or not?):

 - `onComplete` is the right thing to use if you want to react to tween completion
 - `TweenFunction` runs whenever the tweened value changes (so also when the value transitions from 0.99999... to 1.0)
 - `Std.string()` rounds values when converting floats on cpp/neko (see https://github.com/HaxeFoundation/hxcpp/issues/238 - bug or not is open for discussion)
 - the number of tweening steps (calls to `numCallback()`) is the same across targets, and the underlying float value is correct (although its string repr is not)

**Comment by MSGhero** [comment] 2016-07-04 22:46
@azrafe7 Because 0.99 and 1 are two different steps, it takes 7 steps to get to the end even though you'd think it only takes 6 (6 / 60 = 0.1), which is the problem. The addition precision step is different on each platform, so theoretically some platforms on some computers might actually get to 1.0 in 6 steps.

Additionally, if it's taking 6 steps to get to 0.99, I'm not sure if those 6 steps are actually 6/60 of a second, in which case, the 7th step is taking longer than the duration you input as a parameter.

**Comment by azrafe7** [comment] 2016-07-04 23:25
@MSGhero, I agree with most of your positions, but would also like to point out that the initial OP question may be resolved by simply testing the float values, and not relying on their string reps (or - better - resort to use `onComplete`).

Must admit you have a point in saying that the duration time of the tween is extended by one step (bug?!) but, as you pointed out, that's not an easy fix to have cross-platform (different timing/rounding/division), and I think the developer should handle it.

@IBwWG, can you please show us what's your specific use case?

**Comment by IBwWG** [comment] 2016-07-09 17:40
Actually, I had been testing float values, that's where I ran into this bug in the first place.  It's moot for me now because I've already restructured my code--I didn't *have* to have it this way, it's just that it was quite unexpected, and because of that, tricky to debug.  If it doesn't warrant fixing maybe just a quick note in the docs would help someone avoid the same issue, I don't know.  Just trying to help.

**Comment by Gama11** [comment] 2016-07-09 18:11
I agree with @azrafe7 / @MSGhero, there's not much we can do here.

**Closed by Gama11** 2016-07-09 18:11 UTC

**Comment by IBwWG** [comment] 2016-08-24 14:09
Here's a use case: my music isn't fading out properly on flixel 4.1.1.  I added a trace statement, and found the volume doesn't actually reach 0:

```haxe
FlxG.sound.music.fadeOut(0.4, 0, null);
```

```
FlxSound.hx:698: (playing: true | time: 1339.909 | length: 39925.261 | volume: 0.2),0.166666666666667
FlxSound.hx:698: (playing: true | time: 1399.909 | length: 39925.261 | volume: 0.167),0.133333333333333
FlxSound.hx:698: (playing: true | time: 1499.909 | length: 39925.261 | volume: 0.133),0.1
FlxSound.hx:698: (playing: true | time: 1539.909 | length: 39925.261 | volume: 0.1),0.0666666666666667
FlxSound.hx:698: (playing: true | time: 1599.909 | length: 39925.261 | volume: 0.067),0.0333333333333334
```

3% volume may not sound like much, but you can still hear it.

This happens intermittently, even with the same track.

**Comment by IBwWG** [comment] 2016-08-24 15:09
Hmm, worse yet, this workaround doesn't even fire:

```haxe
			FlxG.sound.music.fadeOut(0.4, 0, function(t:FlxTween){
				trace("forcing to 0");
				FlxG.sound.music.volume = 0;
			});
```

The "forcing to 0" never traces.

**Comment by IBwWG** [comment] 2016-08-24 15:12
Another attempted workaround, replacing fadeOut's .num() with a `FlxTween.tween(this, {volume:To}...)` produced the same results.

**Comment by MSGhero** [comment] 2016-08-24 15:50
Well...if that were the case, the `onComplete` callback would never run in any tween for anyone's projects. It seems like you're running into something else.

**Comment by Gama11** [comment] 2016-08-24 16:00
That "forcing to 0" snippet works fine in Mode's `PlayState`.

**Comment by IBwWG** [comment] 2016-08-24 17:36
@MSGhero Not necessarily, like you said earlier in the thread, it could have to do with the start/end/duration combinations.

@Gama11 do you get that too if the starting volume is 0.2?  (And what exactly do you mean by "Mode's PlayState"?)

**Comment by Gama11** [comment] 2016-08-24 17:44
Yes.

https://github.com/Gama11/flixel-demos/commit/5bbef79723bc3a1ccdfeb809a3907eeaa795fa40

**Comment by IBwWG** [comment] 2016-08-24 17:49
Not quite: the first parameter to fadeOut (unlike num) is the duration, not the starting value.  You need `FlxG.sound.music.volume = 0.2;` followed by `...fadeOut(0.4, 0, ...)` for what I'm experiencing.  Although, maybe it's unrelated--I don't think 0.03333333 is a mistaken representation of the float value for 0.  It's as if the last tween step just never happens.

**Comment by Gama11** [comment] 2016-08-24 17:52
I just copied your code snippet. :P

**Comment by IBwWG** [comment] 2016-08-24 17:53
Well, it wasn't in the original, only as a comment, because I don't actually set the volume just before.  That's just where it happens to be by the time the snippet is called, as you can see from the trace :)

**Comment by IBwWG** [comment] 2016-08-24 18:35
Never mind, it's something I was doing, in this case: two simultaneous tweens, one ending in switchstate...which of course, kills the other tween before it can complete.
