### ISSUE TITLE
FlxSpriteGroup.set_alpha borked when setting alpha from 0 to 1

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1870] opened 2016-06-16 11:44 UTC
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:**
windows and flash
________________________________

**Code snippet reproducing the issue**:

```haxe
package;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.group.FlxSpriteGroup;

class PlayState extends FlxState
{
	override public function create():Void 
	{
		var g:FlxSpriteGroup = cast add(new FlxSpriteGroup());
		g.add(cast new FlxSprite());
		g.members[0].makeGraphic(100, 100);
		g.alpha = 0;
		g.alpha = 1;
	}
}

```

________________________________

**Observed behavior:**
Blank.
**Expected behavior:**
Should see white square, as you would if you commented the last two lines out.

**Comment by IBwWG** [comment] 2016-06-16 11:46
This is likely caused by this line in FlxSpriteGroup.hx:

`			var factor:Float = (alpha > 0) ? Value / alpha : 0;`

I have two questions about this:

a) what's the purpose of it?
b) in the above example, how come it doesn't cause a divide by zero error?  instead it passes 0 on as the value of `factor` to the next function, which then sets the alpha to 0, causing the above broken behaviour

**Comment by Gama11** [comment] 2016-06-16 11:51
Duplicate of #1353.

**Closed by Gama11** 2016-06-16 11:51 UTC

**Comment by IBwWG** [comment] 2016-06-16 11:52
Sorry!  I searched before the last bug, forgot to search this time.  With that title I definitely would've found it!  Whoops!
