### ISSUE TITLE
Add support for multi-texture frame collections

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFlixel/flixel#2587] opened 2022-06-22 01:26 UTC
For the purposes of optimization, it would be useful to have the ability to initialize a character's animations by creating a frame collection which is able to pull from two or more spritesheets.

For example, if you have some levels where a character needs some extra animations and other levels where these extra animations are not needed, you can place the primary animations in one Sparrow spritesheet and the secondary animations in an additional Sparrow spritesheet. Then the sprite would use the appropriate sprite and coordinates for the appropriate frame.

This is one manner it may appear to people using the feature:

```haxe
var primaryFrameCollection:FlxAtlasFrames = FlxAtlasFrames.fromSparrow(primaryImage, primaryData);

var finalFrameCollection:FlxAtlasFrames = primaryFrameCollection;

if (needsSecondaryAnimations) {
  var secondaryFrameCollection = FlxAtlasFrames.fromSparrow(secondaryImage, secondaryData);
  finalFrameCollection= FlxAtlasFrames.concatenate([primaryFrameCollection, secondaryFrameCollection]);
}

sprite.frames = finalFrameCollection;

// Both of these should work.
sprite.play('animFromPrimaryCollection');
sprite.play('animFromSecondaryCollection');
```

In this case, we are able to create a sprite that includes both sets of animations, without `secondaryImage` having to include the frames from `primaryImage`.

**Comment by Geokureli** [comment] 2022-06-22 20:21
does sparrow always have a 1:1 image/data  export? I thought there was a way to export multiple sheets with a single data file listing the frames of each image. otherwise I would expect different animations that share frames to export the same frame to multiple images.

**Comment by NeeEoo** [comment] 2022-07-09 23:22
You can achieve the desired result using

```haxe
function addFrames(otherFrames:FlxFramesCollection, reload:Bool = true) {
	if(otherFrames == null) return;

	for(frame in otherFrames.frames) {
		this.frames.pushFrame(frame);
	}

	if(reload) {
		this.frames = this.frames;
	}
}
```

**Comment by MasterEric** [comment] 2022-07-09 23:29
@NeeEoo does this work when there are multiple images? I remember there being some issues with that.

@Geokureli I agree, this is a good target for Flixel addons

**Comment by NeeEoo** [comment] 2022-07-09 23:31
Yea, it works with any amount, a sprite/character in a project im in uses 3 spritesheets (png + xml) due to the amount of frames it has.

**Comment by MasterEric** [comment] 2022-07-09 23:39
Ah that's interesting! I'll have to test it for myself. If it works, that
looks simple enough to add to base Flixel without too much bloat.

**Comment by MasterEric** [comment] 2022-10-20 05:09
> You can achieve the desired result using
> 
> ```hx
> function addFrames(otherFrames:FlxFramesCollection, reload:Bool = true) {
> 	if(otherFrames == null) return;
> 
> 	for(frame in otherFrames.frames) {
> 		this.frames.pushFrame(frame);
> 	}
> 
> 	if(reload) {
> 		this.frames = this.frames;
> 	}
> }
> ```

Just a quick check-in, I tried this method and it 1000% worked as expected. Since frame collections can easily be reused between sprites, this is VERY powerful for improving efficiency.

I'll maybe make a PR to add this function to the FramesCollection proper then close this issue after I do that.

**Comment by Geokureli** [comment] 2023-03-09 02:02
@EliteMasterEric @SeiferTim have there been major breakthroughs in adding this functionality to flixel? Both of you said you needed to use this for a personal project, and both of your projects seem to be past the prototyping phase. If it's as straightforward as i hoped i would like to include it in the 5.3 release

**Comment by EliteMasterEric** [comment] 2023-03-09 03:08
It's not any functionality that needs any significant work; you can already manually add frames (that possibly use a different graphic) and it'll work. Just adding something like the function NeeEeo suggested would be sufficient since it's not obvious right now that you can do it.

**Comment by ACrazyTown** [comment] 2023-03-09 15:37
Btw, I had an issue with multi-texture frame collections via the method above in a project that featured a caching system (a simple `Map<String, FlxGraphic>` in which `String` is the path to the asset) where calling an animation from the secondary atlas would crash the game sometimes.
I fixed it by also caching the secondary atlas's `parent`.

It might just be an issue with my project though, wanted to say this just in case

**Comment by Geokureli** [comment] 2023-03-09 15:45
@ACrazyTown is that project public? could you share some textures with some snippets showing the caching system you tried

**Comment by ACrazyTown** [comment] 2023-03-09 15:58
> @ACrazyTown is that project public? could you share some textures with some snippets showing the caching system you tried

It isn't. I'll try to make a demo showcasing the issue (if I can reproduce it) in a couple days

**Closed** 2023-10-10 23:07 UTC
Labels: New Feature
