### ISSUE TITLE
FlxCamera transparent background is rendered as black (or crashes)

### ISSUE THREAD

**Issue by mikeevmm** [HaxeFlixel/flixel#1981] opened 2016-10-16 17:15 UTC
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1 (with -Dnext)
- **Lime version:** 2.9.1
- **Affected targets:** Desktop

---

**Code snippet reproducing the issue**:

``` haxe
package;

import flixel.FlxState;
import flixel.util.FlxColor;
import flixel.FlxG;

class PlayState extends FlxState
{
    override public function create():Void
    {
        FlxG.camera.bgColor = FlxColor.GREEN; // For example
        var camera:FlxCamera = new FlxCamera();
        camera.bgColor = FlxColor.TRANSPARENT; // Or 0x0
        FlxG.cameras.add(camera);
    }
}
```

---

**Observed behavior:**

Varies between black background on `camera`:
(From real project; in this case the camera with the blur filter applied is hidden by the black `bgColor` of the HUD camera:)

**Observed behavior:**

![image](https://cloud.githubusercontent.com/assets/7550678/19419230/157b46aa-93cb-11e6-8760-c4a5229d9815.png)

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/7550678/19419229/10737434-93cb-11e6-9b77-bda701c23c8e.png)

and project crash altogether, in the case of the issue-isolating project (although some testers also reported crashing on the main project):

**Observed behavior:**

> <Exe name>.exe has stopped working

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/7550678/19419276/0fd96b9a-93cc-11e6-9188-41df04e2a32c.png)

**Details:**

After examining graphics cards models, it seems that everyone that experiences crashes has an Intel Graphics Card. Testers with GeForce and Radeon have ~~no issues~~. A tester with a `gtx 970` reported a crash on the test project, but runs the original project fine.
##

**Comment by mikeevmm** [comment] 2016-10-16 17:15
I also apologize for the weird issue, but `-Dnext` seems prone to this kind of stuff.

**Comment by Gama11** [comment] 2016-10-16 19:30
I can't seem to reproduce that. Both neko -Dnext and cpp -Dnext show the expected result.

There were some issues with camera bg colors on next, but those shouldn't happen anymore: https://github.com/HaxeFlixel/flixel/issues/1793

**Comment by mikeevmm** [comment] 2016-10-16 22:19
Yeah, I experienced the #1792 issues too, this latest release fixed that.

What's your Graphics Card mode (if l might ask)?

**Comment by DleanJeans** [comment] 2016-10-16 23:21
I also get a black background instead of a semi transparent black background on Android. Works fine in Flash. Not tested in others.

**Comment by JoeCreates** [comment] 2016-10-17 02:54
Have you tried removing all shaders andcfilters from the project? Ive had issues with shaders on intel graphics card which eezulted in the camera with the filterbrendering black.

**Comment by mikeevmm** [comment] 2016-10-17 07:02
@JoeCreates oddly enough, the camera causing the crashes/with a black bg has no shaders applied to it.

There are also no shaders on the issue isolating project, and crash reports were pretty consistent with it.

**Comment by mikeevmm** [comment] 2016-10-17 07:03
@DleanJeans just wanted to point out you should get either solid green or solid black on any target, not semi-transparency.

**Comment by Gama11** [comment] 2016-10-17 08:26
>What's your Graphics Card (if l might ask)?

Radeon HD 6850

**Comment by mikeevmm** [comment] 2016-10-17 08:52
@Gama11 Could you confirm you cannot reproduce the issue on a computer with an Intel gfx card (if you have access to one, obviously)?

**Comment by Gama11** [comment] 2016-10-17 10:12
My laptop has an Nvidia card as well as an integrated Intel card. When I set the preferred graphics processor in the Nvidia control panel to "Integrated graphics", I still get the expected result.

**Comment by mikeevmm** [comment] 2016-10-17 12:37
@gama11 huh... I'm at a loss then, it crashed on 4/6 pcs on our team, but I have no idea on what might be causing it...

Intel HD Graphics, Windows 10?

**Comment by MSGhero** [comment] 2016-10-17 12:50
What version Intel HD? I had general issues on my old laptop, whatever version that was. My drivers also couldn't update. Now I'm on the most recent iteration with the latest drivers.

**Comment by mikeevmm** [comment] 2016-10-17 13:06
@MSGhero everything from 4000, 4600, and no number (plain Intel Graphics HD).

Did you manage to update the drivers and get it to work or did you change gfx card/pc?

**Comment by Gama11** [comment] 2016-10-17 13:07
4400 on Windows 7 on my Laptop.

**Comment by mikeevmm** [comment] 2016-10-17 13:13
@Gama11 Ah, then it's likely it's a windows 10 thing... sigh.

I'll have the others run the exe in compatibility mode and get back to you.

**Comment by JoeCreates** [comment] 2016-10-17 14:59
@mikeevmm Worth noting that a whole load of Intel graphics cards are still not officially supported by Windows 10. There was a ridiculous error in the windows upgrading software that checks for compatibility which ended up auto-updating many people to windows 10 in spite of their machines not being compatible. Intel, I think, have finally released a fixed version after way too long, but many devices such as laptops require the laptop manufacturer to produce their own versions. I'm suffering from many issues due to this right now.

**Comment by mikeevmm** [comment] 2016-10-17 17:21
@JoeCreates sigh, after windows 8, windows 10 looked promising.

Thank you for the info.

**Comment by mikeevmm** [comment] 2016-10-17 17:32
Compatibility mode didn't help.

**Comment by mikeevmm** [comment] 2016-10-17 18:04
@Gama11 One of the members just confirmed that switching from Intel to an Nvidea gfx card solves the problem, but another just pointed out that he's using windows 8.1, so it's *definitely* an Intel problem.

**Comment by mikeevmm** [comment] 2016-10-17 18:10
Okay, so much for sanity:

Running a build of the issue-isolating problem with `hardware` set to `false` on `Project.xml` causes crashes on *every* PC, including non-Intel ones. However, running the exe in compatibility mode prevents that crash.

Help.

@Gama11 Could you confirm this?

**Comment by Gama11** [comment] 2016-10-17 19:12
I don't get a crash with `hardware="false"` on my PC (which is Win10). Haven't tested on my Laptop yet.

**Comment by mikeevmm** [comment] 2016-10-17 20:35
@Gama11 Oh, I just thought of something: are you compiling with haxe `3.2.1` or `3.3.0`?

**Comment by mikeevmm** [comment] 2016-10-23 18:53
Compiling with `Haxe 3.3.0-rc1` does not prevent crashing on Intel machines.

**Comment by starry-abyss** [comment] 2016-10-23 18:58
Maybe this is your case (see answer)? https://twitter.com/IgorsGames/status/732295259540099072

**Comment by mikeevmm** [comment] 2016-10-23 19:02
@starry-abyss Might very well be, since I've been getting the feeling that it's an Intel/OpenGL combo issue.

I'll try this and report later, thank you.

**Comment by mikeevmm** [comment] 2016-10-23 21:08
@starry-abyss I can't seem to get a build to work with -Dangle, unfortunately.

Did you get this to work?

**Comment by starry-abyss** [comment] 2016-10-23 23:36
I think, no. But it wasn't the root of my problem anyway.
We can invite @larsiusprime himself here I guess.

**Comment by mikeevmm** [comment] 2016-10-29 22:40
Bumping @larsiusprime , because I have no idea how to go about this.

**Comment by larsiusprime** [comment] 2016-10-31 14:01
Oh, Intel graphics, bane of my existence.

In order to build with "-Dangle" you ALSO have to rebuild lime itself from source. 

1. Make sure you have the right version of lime installed from github
2. Rebuild lime w/ Angle: ```lime rebuild windows -DLIME_SDL_ANGLE```
3. Rebuild your project: ```lime test windows -Dnext -Dangle```

You might need to stick "-clean" on those commands if something goes wrong.
Also remember that ANGLE only exists on windows. It's basically translating OpenGL to DirectX.

To verify at run-time that your program is indeed using the ANGLE renderer, do this:
```var GLVersion = lime.graphics.opengl.GL.getParameter(lime.graphics.opengl.GL.VERSION);```

This will return a string that will have "ANGLE" in it somewhere if ANGLE is active.

**Comment by mikeevmm** [comment] 2016-11-01 21:50
@larsiusprime Haven't had time to test this yet, but dropping by to thank you and acknowledging

**Comment by mikeevmm** [comment] 2016-11-02 18:58
@larsiusprime Hmm, lime rebuilding works fine (tool rebuild throws no warnings either), but I get an error upon compiling if I'm using lime `dev 2.9.1`:

```cmd
Called from ? line 1
Called from CommandLineTools.hx line 1400
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 619
Called from lime/project/PlatformTarget.hx line 70
Called from lime/tools/platforms/WindowsPlatform.hx line 318
Called from lime/tools/helpers/FileHelper.hx line 383
Called from lime/tools/helpers/FileHelper.hx line 366
Called from lime/tools/helpers/FileHelper.hx line 150
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 110
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 369
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 385
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 369
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 356
Called from E:\HaxeToolkit\haxe\std/haxe/Template.hx line 120
Called from E:\HaxeToolkit\haxe\std/neko/_std/Reflect.hx line 25
Uncaught exception - Invalid field access : __s
```

**Comment by Gama11** [comment] 2017-05-21 16:33
It doesn't look like there's much we can do about this, at least on Flixel's end, so I'll go ahead and close this.

**Closed by Gama11** 2017-05-21 16:33 UTC
Labels: Can't reproduce
