### ISSUE TITLE
Background Tile Artifacts Using  flixel.addons.editors.tiled.TiledMap

### ISSUE THREAD

**Issue by AliceGrey** [HaxeFlixel/flixel#1514] opened 2015-05-27 03:37 UTC
When I compile my game using a background layer the background layer tears but only in fullscreen.
Small screen
![No Artifacts](http://i.imgur.com/POFmAQE.png?1)

Fullscreen
![Artifacts](http://i.imgur.com/ERJUTsq.png?1)
Here is my TiledMap Code (based on the demo)

```
// For each "Tile Layer" in the map, you must define a "tileset" property which contains the name of a tile sheet image
// used to draw tiles in that layer (without file extension). The image file must be located in the directory specified bellow.
    private inline static var c_PATH_LEVEL_TILESHEETS = "assets/art/";

// Array of tilemaps used for collision
    public var foregroundTiles:FlxGroup;
    public var backgroundTiles:FlxGroup;
    public var tileSheet:String;
    public var tileSize:Int;
    private var collidableTileLayers:Array<FlxTilemap>;
    public function new(tiledLevel:Dynamic, tileSheet:String, tileSize:Int) {
        super(tiledLevel);
        this.collidableTileLayers = [];
        this.tileSheet = tileSheet;
        this.tileSize = tileSize;
        foregroundTiles = new FlxGroup();
        backgroundTiles = new FlxGroup();
        FlxG.camera.setBounds(0, 0, fullWidth, fullHeight+80, true);

        var bglayer:FlxTilemap = loadLayer("nocollide");
        backgroundTiles.add(bglayer);
        var layer:FlxTilemap = loadLayer("Map");
        collidableTileLayers.push(layer);
        foregroundTiles.add(layer);
    }
    public function loadLayer(layer:String):FlxTilemap {
        var result:FlxTilemap;
        for ( tileLayer in layers ) {
            if (tileLayer.name != layer) continue;
            var imagePath = new Path(tileSheet);

            var processedPath = c_PATH_LEVEL_TILESHEETS + imagePath.file + "." + imagePath.ext;
            var tilemap:FlxTilemap = new FlxTilemap();
            tilemap.widthInTiles = width;
            tilemap.heightInTiles = height;
            tilemap.loadMap(tileLayer.tileArray, processedPath, tileSize, tileSize, 0, 1, 1, 1);
            return tilemap;
        }
        throw 'Couldn\'t find layer named $layer';
        return null;
    }





    public function loadObjects(state:PlayState)
    {
        for (group in objectGroups)
        {
            for (o in group.objects)
            {
                loadObject(o, group, state);
            }
        }
    }

    private function loadObject(o:TiledObject, g:TiledObjectGroup, state:PlayState)
    {
        var x:Int = o.x;
        var y:Int = o.y;



        // objects in tiled are aligned bottom-left (top-left in flixel)
        if (o.gid != -1)
            y -= g.map.getGidOwner(o.gid).tileHeight;

        switch (o.type.toLowerCase())
        {
            //case "player_start":
            //    var player = new Player(120, 60, state, _computiegibs, _bullets);
            //    state.add(player);
            case "floor":
                var floor = new FlxObject(x, y, o.width, o.height);
                state.floor = floor;

            case "coins":
                var tileset = g.map.getGidOwner(o.gid);
                var coin = new Coin(x, y);
                state.coins.add(coin);
            case "exit":
// Create the level exit
                var exit = new FlxSprite(x, y);
                exit.makeGraphic(32, 32, 0xff3f3f3f);
                exit.exists = false;
                state.exit = exit;
                state.add(exit);
        }
    }


    public function collideWithLevel(obj:FlxObject, ?notifyCallback:FlxObject->FlxObject->Void, ?processCallback:FlxObject->FlxObject->Bool):Bool
    {
        if (collidableTileLayers != null)
        {
            for (map in collidableTileLayers)
            {

               // return FlxG.collide(map,obj,notifyCallback);
// IMPORTANT: Always collide the map with objects, not the other way around.
//			  This prevents odd collision errors (collision separation code off by 1 px).
                return FlxG.overlap(map, obj, notifyCallback, processCallback != null ? processCallback : FlxObject.separate);
            }
        }
        return false;
    }
```

and this is how I call it

```
level = new TiledLevel("assets/tiled/level1n.tmx","assets/art/level1.png",16);
        //Reg.map = level;
        add(level.backgroundTiles);
        // Add tilemaps
        add(level.foregroundTiles);

        // Draw coins first
        coins = new FlxGroup();
        add(coins);
         // Load player objects
        level.loadObjects(this);
```

**Comment by Gama11** [comment] 2015-05-27 06:41
Same issue as #911?

**Comment by AliceGrey** [comment] 2015-05-27 07:27
It's possible but none of those fixes worked for it. And that bug supposively only happens on cpp targets and while moving. This happens on neko aswell as cpp even if you don't move.

**Comment by Gama11** [comment] 2015-05-27 07:29
There isn't really much of a difference between neko and cpp when it comes to rendering, and when you speak about "cpp targets", neko is often included (though the `#if cpp` define technically doesn't include it).

**Comment by AliceGrey** [comment] 2015-05-27 07:34
Oh I didn't know that. Do you have any ideas on how I could fix this for my project? 

On May 27, 2015 12:29:50 AM PDT, Gama11 <notifications@github.com> wrote:
>There isn't really much of a difference between neko and cpp when it
>comes to rendering, and when you speak about "cpp targets", neko is
>often included (though the `#if cpp` define technically doesn't include
>it).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/HaxeFlixel/flixel/issues/1514#issuecomment-105798388

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Gama11** [comment] 2015-05-27 07:37
I would suggest trying the fixes in that issue.. You've tried all of them?

`FlxTilemap` also has a `tileScaleHack` property to work around tearing. You could try playing around the values of that.

**Comment by Ohmnivore** [comment] 2015-05-27 15:41
This really id the job for me: https://gist.github.com/Ohmnivore/41eaca877d202b875b65

**Comment by AliceGrey** [comment] 2015-05-27 19:14
@Gama11 So far I retried FlxG.camera.pixelPerfectRender = false; and turning antialias off which gave me this error:
```
flixel.FlxCamera has no field pixelPerfectRender
```
and I retried tileScaleHack and that didn't help either.

@Ohmnivore 
When I call artefactfix I seem to get thsi error. Do you know waht I'm doing wrong?
``` Type name TestFeatures is redefined from module Fix```
This is how I call it:
```
tilemap.loadMap(tileLayer.tileArray, TestFeatures.artefactFix("assets/art/level1.png", 16, 16), tileSize, tileSize, 0, 1, 1, 1);
```

**Comment by Gama11** [comment] 2015-05-27 19:17
`FlxCamera#pixelPerfectRender` is only available on the dev branch, but technically it's only for convienence, individual sprites should still have that property.

How did you name the .hx file with the `TestFeatures` class?

**Comment by AliceGrey** [comment] 2015-05-27 19:19
@Gama11 
I named it Fix.hx

**Comment by Gama11** [comment] 2015-05-27 19:30
A Haxe-module (.hx file) can not have an arbitrary name - there has to be one type in it whose name matches the file name (doesn't have to be a class, could be a typedef, abstract or enum too).

It worked as in "it now compiles" or "it fixes your issue"?

**Comment by AliceGrey** [comment] 2015-05-27 19:30
@Gama11 

Thanks, that's good to know.

As in it now compiles and fixes my issue.

**Comment by Gama11** [comment] 2015-05-27 19:31
Closing this then, since that probably means this is just a duplicate of #911 which is still open.

**Closed** 2015-05-27 19:31 UTC

**Comment by Ohmnivore** [comment] 2015-05-27 22:58
Tested with haxeflixel v3.3.8

Also works for loading sprites (I've had the issue appear on sprite animations as well - they're tilesheets too)

**Usage**:
```
loadMap(tempData, ArtifactFix.artefactFix("images/tiles.png", TILESIZE, TILESIZE),
			TILESIZE, TILESIZE, FlxTilemap.OFF, 0, 1, 1);
```

```
package util;
import flash.display.BitmapData;
import flash.geom.Point;
import flash.geom.Rectangle;
import flixel.FlxG;
import flixel.util.loaders.CachedGraphics;
import flixel.util.loaders.TextureRegion;
import flixel.system.layer.Region;

/**
 * ...
 * @author Ohmnivore
 */
class ArtifactFix
{

	static public function artefactFix(Graphic:Dynamic, FrameWidth:Int, FrameHeight:Int):TextureRegion 
	{
		var cached:CachedGraphics = FlxG.bitmap.add(Graphic, false);
		
		var cont:BitmapData = ArtifactFix.returnContainer(cached.bitmap.width, cached.bitmap.height, FrameWidth, FrameHeight);
		ArtifactFix.placeTiles(cached.bitmap, cont, FrameWidth, FrameHeight);
		ArtifactFix.placeSafePixelColumn(cached.bitmap, cont, FrameWidth, FrameHeight);
		
		var newcached:CachedGraphics = FlxG.bitmap.add(cont, true);
		
		//top left corner of the first tile
		var startX:Int = 1;
		var startY:Int = 1;
		//tile size
		var tileWidth:Int = FrameWidth;
		var tileHeight:Int = FrameHeight;
		//tile spacing
		var spacingX:Int = 2;
		var spacingY:Int = 2;
		//end of tiles
		var width:Int = Std.int(cont.width - startX);
		var height:Int = Std.int(cont.height - startY);
		//return region
		return new TextureRegion(newcached, startX, startY, tileWidth, tileHeight, spacingX, spacingY, width, height);
	}
	
	static public function placeSafePixelColumn(Source:BitmapData, Dest:BitmapData, TileWidth:Int, TileHeight:Int):Void
	{
		var border:Int = 1;
		var x_tot:Int = Std.int(Source.width / TileWidth);
		var y_tot:Int = Std.int(Source.height / TileHeight);
		var x_count:Int = 0;
		var y_count:Int = 0;
		
		while (x_count < x_tot)
		{
			while (y_count < y_tot)
			{
				//To the right
				var rect:Rectangle = new Rectangle(x_count * TileWidth - 1, y_count * TileWidth,
					1, TileHeight);
				var point:Point = new Point(border + x_count * TileWidth + x_count * 2 - 2,
					border + y_count * TileHeight + y_count * 2);
				Dest.copyPixels(Source, rect, point, true);
				
				//To the bottom
				var rect2:Rectangle = new Rectangle(x_count * TileWidth, y_count * TileWidth - 1,
					TileWidth, 1);
				var point2:Point = new Point(border + x_count * TileWidth + x_count * 2,
					border + y_count * TileHeight + y_count * 2 - 2);
				Dest.copyPixels(Source, rect2, point2, true);
				
				y_count++;
			}
			
			y_count = 0;
			x_count++;
		}
	}
	
	static public function placeTiles(Source:BitmapData, Dest:BitmapData, TileWidth:Int, TileHeight:Int):Void
	{
		var border:Int = 1;
		var x_tot:Int = Std.int(Source.width / TileWidth);
		var y_tot:Int = Std.int(Source.height / TileHeight);
		var x_count:Int = 0;
		var y_count:Int = 0;
		
		while (x_count < x_tot)
		{
			while (y_count < y_tot)
			{
				var rect:Rectangle = new Rectangle(x_count * TileWidth, y_count * TileWidth,
					TileWidth, TileHeight);
				var point:Point = new Point(border + x_count * TileWidth + x_count * 2,
					border + y_count * TileHeight + y_count * 2);
				Dest.copyPixels(Source, rect, point, true);
				
				y_count++;
			}
			
			y_count = 0;
			x_count++;
		}
	}
	
	static public function returnContainer(Width:Int, Height:Int, TileWidth:Int, TileHeight:Int):BitmapData
	{
		var width:Int = Width + (Std.int(Width / TileWidth) - 1) * 2 + 2;
		var height:Int = Height + (Std.int(Height / TileHeight) - 1) * 2 + 2;
		
		return new BitmapData(width, height, true, 0x00ffffff);
	}
	
}
```

**Comment by Ohmnivore** [comment] 2015-05-27 22:58
If it don't work call #911

**Comment by Ohmnivore** [comment] 2015-05-27 22:59
oh lol just read u had it figured out, sry
