### ISSUE TITLE
Sound cutting out after playing 255 times on cpp target

### ISSUE THREAD

**Issue by pizzamakesgames** [HaxeFlixel/flixel#1645] opened 2015-10-26 11:26 UTC
I have only been encountering this error on the cpp target, not neko.

Using FlxTypeText, typing out text letter by letter, with a sound playing each time, the typing sound effect cuts out after exactly the 255th character, happening pretty consistently. There are no errors. Sometimes it's only happening to the sound being played and the music keeps on running while the sound cuts out, sometimes the music cuts out along with the sound or a while after.
The sound comes back on various actions like un/refocusing the game window or randomly on it's own.

Weirdly, it's happening about every 255 characters when just typing away, resolving itself and re-happening indefinitely. Though, when trying to record the issue, it won't ever happen, not even up to a character/sound count of 2500 and above. The recording software (OBS) just has to be open, and the error won't happen, but as soon as I close it, it'll happen right away. A thing to note might be that OBS sets the Windows 7 color scheme to basic on launch, disabling aero. If I close the software and do this myself, apparently the error doesn't happen either.

Here's a windows demo of the issue if anybody wants to ascertain the aero thing for themselves: https://www.dropbox.com/s/yqhw7dzewcgzb5u/Skullz2SoundError.rar

**Comment by SeiferTim** [comment] 2015-10-26 13:54
How are you playing your sound? Do you have a single `FlxSound` object that you are using again and again, or, are you creating a new one each time, and, if so, are you cleaning them up when they're finished?

**Comment by pizzamakesgames** [comment] 2015-10-26 14:24
In the Project.xml:

```
	<assets path="assets/sounds" unless="flash">
	<sound path="skulltalk1.ogg" id="typesfx1" />
	</assets>
```
In the TextBox.hx (custom class, responsible for handling my text in-game)
```
	public var TypeSFX:FlxSound;

	public function CreateTextBox():Void
	{
		TypeSFX = FlxG.sound.load("typesfx1");
	}
```
In the FlxTypeText.hx (part of flixel-addons, responsible for iterating over each character etc.)
```
	if (sound != null)
	{
		if ((_finalText.charAt( _length ) != " ")
		{
			sound.play(true);
		}
	}
```

For how FlxTypeText handles the sound, see here: https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/text/FlxTypeText.hx

Thank you and regards.

**Comment by pizzamakesgames** [comment] 2015-12-03 20:40
The error persists. Here is a build of the game reproducing the issue: https://www.dropbox.com/s/ybjyrx193n0hlnd/SkullznSkelzsoundissue.rar

You just have to hit space, then let it roll. If the error doesn't happen at first, pressing down to select the second option and thus triggering a conversation using a different sfx seems to help in bringing the issue up.

**Comment by pizzamakesgames** [comment] 2015-12-03 21:33
Managed to make the cpp build throw this single error based on the issue:
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Gama11** [comment] 2015-12-03 21:55
I'd try to see if you can reproduce that outside of flixel, since it's much more likely to be a Lime or OpenFL problem.

**Comment by pizzamakesgames** [comment] 2015-12-08 15:46
It most definitely seems to be an OpenFL/OpenAL issue. Been able to make the issue throw this error:

![image](http://i.imgur.com/wcBmxv2.png)

**Comment by Gama11** [comment] 2015-12-08 16:50
You should open an issue on the Lime or OpenFL repo with a reproducible example.

**Comment by pizzamakesgames** [comment] 2015-12-08 17:54
Actually I've just tried the FlxTypeText from the master branch flixel-demos, and it's happening there as well. Just compile it to windows, let it type a bit and it'll crash, throwing the AL lib: (EE) alc_cleanup: 1 device not closed error.

**Comment by azrafe7** [comment] 2015-12-11 23:27
I've been successful in reproducing this with pure OpenFl, but under _somewhat_ specific circumstances.

A gist is here: https://gist.github.com/azrafe7/d49f26f2411e1c9b83a3

The issue is present only for CPP legacy. I'm testing it on win7 with haxe 3.2.1 and with a slightly outdated versions of lime and openfl (git versions before the ByteArray changes). Not sure if might be related, but I've only tested with `--window-hardware=false` (I have an old graphics card!).

One interesting thing to note is that if I uncomment the `<window fps="60" />` line in project.xml it works fine for me, but the same _fix_ isn't valid for the FlxTypeText demo.

Tring to isolate the issue I've added some traces into the cpp code interfacing with OpenAL. 
In `lime\legacy\project\src\openal\OpenALSound.cpp`:

adding

```LOG_SOUND("mSourceID: %d", mSourceID);```

at the end of `OpenALChannel::OpenALChannel`, and uncommenting

```LOG_SOUND("OpenALChannel destructor %d", mSourceID);```

in `OpenALChannel::~OpenALChannel()`


The log shows that after ~256 played sounds, `mSourceID` is zero (so invalid). The problem could well be dued to some race conditions (as in some of my tests the destructors were correctly called on the channels, not sure why).

Sorry for the ?confusing exposition so far (just throwing out thoughts!) but, to sum up:

 - mSourceID is invalid at some point (after ~256 plays)
 - destructor/isComplete is not correctly called (buffers/ids not reused)
 - timings/threads might be responsible for the behaviour
 - only CPP legacy is involved (-Dnext and other targets work fine (also neko!))

**Comment by azrafe7** [comment] 2015-12-12 19:53
Investigating more it seems that the problem is related to the GC not kicking in fast enough.

If you try the updated [gist](https://gist.github.com/azrafe7/d49f26f2411e1c9b83a3) and press space when the sound goes off, the GC will be forced to release the channels, and sound should work again. 

@pizzamakesgames: you can also try it in your own case by adding:

```haxe
	#if cpp
		cpp.vm.Gc.run(false);
	#end
```

Obviously this would only be a workaround (force-fire the GC based on some heuristic), so there's still the need for a proper fix.

**Comment by pizzamakesgames** [comment] 2015-12-14 12:05
Thank you very much! I've referenced your comment in the [OpenFL thread](http://community.openfl.org/t/sound-cutting-out-after-256-plays-on-windows-cpp-target/7074/3?u=pizzamakesgames) about the issue, hopefully making the OpenFL dev's life a bit easier.

You've been mentioning using -Dnext, using lime and openfl versions before the ByteArray changes. Personally, I wouldn't mind using Dnext in general, if it solves this particular issue without introducing any new ones, though I've been getting an error eluding to that ByteArray change when trying to use Dnext. Would you think it was worth trying to get that particularly error sorted out and just continue using Dnext henceforth, or would that end up being too unstable a setup for a final release and I'd be better off waiting for a fix of the legacy version?

Thank you for your help thus far and regards.

**Comment by Gama11** [comment] 2015-12-20 22:38
Closing this since it's an OpenFL bug and we can't do much about it on Flixel's side.

Thanks to @azrafe7 for isolating this so well.

**Closed by Gama11** 2015-12-20 22:38 UTC
Labels: Bug, OpenFL / Lime

**Comment by pizzamakesgames** [comment] 2015-12-21 09:33
Thank you all very much!

**Comment by azrafe7** [comment] 2015-12-22 09:21
np! :smile:

**Comment by azrafe7** [comment] 2015-12-22 10:12
Maybe I've found a way to solve this (at least it seems to work for me).

Change [`bool OpenALChannel::isComplete()`](https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L265) to:
```haxe
   bool OpenALChannel::isComplete()
   {
      bool complete = false;
	  
	  if (mUseStream)
      {
         if -(mStream)
         {
            mStream->update();
            complete = !(mStream->isActive());
         }
         else
         {
            complete = true;
         }
      }
      else if (!mSourceID)
      {
         //LOG_SOUND("OpenALChannel isComplete() - never started!");
         complete = true;
      }
      else if (!mDynamicDone)
	  {
         complete = false;
	  }
	  else
	  {
		  // got this hint from
		  // http://www.gamedev.net/topic/410696-openal-how-to-query-if-a-source-sound-is-playing-solved/
		  ALint state;
		  alGetSourcei(mSourceID, AL_SOURCE_STATE, &state);
		  /*
		   Possible values of state
		   AL_INITIAL
		   AL_STOPPED
		   AL_PLAYING
		   AL_PAUSED
		   */
		  if(state == AL_STOPPED)
		  {
			 if (mLoops > 0)
			 {   
				float seek = 0;
				
				if (mStartTime > 0)
				{
				   seek = (mStartTime * 0.001) / mLength;
				}
				
				if (seek < 1)
				{
				   //alSourceQueueBuffers(mSourceID, 1, &inBufferID);
				   alSourcePlay(mSourceID);
				   alSourcef(mSourceID, AL_BYTE_OFFSET, seek * mSize);
				}
				
				mLoops --;
				
				complete = false;
			 }
			 else
			 {
				complete = true;
			 }
			 //LOG_SOUND("OpenALChannel isComplete() returning true");
		  }
		  else
		  {
			 //LOG_SOUND("OpenALChannel isComplete() returning false");
			 complete = false;
		  }
	  }
	  
	  if (complete && mSourceID)
	  {
		 alDeleteSources(1, &mSourceID);
	  }
	  
	  return complete;
   }
```

And [`these two lines`](https://github.com/openfl/openfl/blob/d0f584c91d763384805ee69a8152ac73c4799552/openfl/_legacy/media/SoundChannel.hx#L248-L249) in ` __runCheckComplete ()` to:
```haxe
    stop();
```

@Gama11, @pizzamakesgames (and anyone interested), can you please check if it works on your end too? Still not sure it's the proper fix (but seems more or less how next handles hit too, calling alDeleteSource on channel stop()).

PS: Don't forget to rebuild: `lime rebuild neko -Dlegacy`.

**Comment by azrafe7** [comment] 2015-12-22 11:29
Oh... didn't notice this was closed. Cross posting latest findings to https://github.com/openfl/openfl/issues/962.
