### ISSUE TITLE
FlxSpriteGroup positioning issues

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFlixel/flixel#1206] opened 2014-07-01 23:09 UTC
`FlxSpriteGroup` has a couple of issues relating to the way it tries to update the properties of member sprites, such as their positions. Currently, when a `FlxSpriteGroup`s position changes, it adds the same difference to each member sprites position.

The first issue is that it means member sprites end up jittering (for the same reason that previously all sprites jittered). Previously, a sprite's render position was a combination of the cameras position and its position, which caused jittering when the real parts of each added to more than one. With `FlxSpriteGroup`, the sprites position is a combination of it's original position plus the position of the sprite group, so the same effect comes about when the real parts of each add to more than one. With `FlxSpriteGroup`, however, there is no way to floor the sprites position if `pixelPerfectPosition` is true, because the sprite's position relative to the sprite group would be lost by any such flooring. 

The second issue is that updating each sprite's position by the change in the group's position results in a gradual loss of precision due to floating point imprecision. If a sprite group moves a lot, small floating point discrepancies can accumulate to become very noticeable. Once again, it is not possible to solve this by any kind of rounding, because doing so would lose the sprite's position relative to the group.

I'm not sure of the best way to solve these, though one option might be to give `FlxSprite` a relativeX and relativeY (or relativePosition) property, along with a parent sprite, which in turn keeps a record of its children. When the parent sprite changes position, it updates each child's position to the parent's position plus the child's relative position. With this method, every sprite would effectively become a sprite group. You could attach any sprite to any other, for example, a sword to a player. Alternatively, only `FlxSpriteGroup` could be given the ability to attach sprites, though every sprite would still need a relative position and parent.

With something like this, if a sprite's position is updated on its own, this would be lost when it's parent group moves. Instead, moving the sprite inside the group would require changing the relative position. Perhaps it would be possible to allow the relative position of the sprite to change if something other than the parent sprite group tries to change a sprites position?

It's a fairly tricky problem, so I'm keen to hear other suggestions.

**Comment by Gama11** [comment] 2016-02-07 20:14
This seems like a duplicate of #975 - as mentioned there, I don't think expanding the already hacky sprite groups further with matrices etc is the right approach. `FlxNestedSprite` seems cleaner in that regard.

**Closed by Gama11** 2016-02-07 20:14 UTC
Labels: Bug
