### ISSUE TITLE
FlxFramesCollection.getIndexByName() method

### ISSUE THREAD

**Issue by DrDerico** [HaxeFlixel/flixel#1497] opened 2015-05-17 09:16 UTC
This method is inlined now. So the game can't be compiled with this error:
"flixel/graphics/frames/FlxFramesCollection.hx:105: characters 4-12 : Cannot inline a not final return"

So I propose to make getIndexByName() not inlined. What do you think?

**Comment by Gama11** [comment] 2015-05-17 09:47
Target? Flixel version? Haxe version?

**Comment by DrDerico** [comment] 2015-05-17 09:50
Sorry.
Haxeflixel - dev
Target: all
Haxe: 3.0.2

**Comment by Gama11** [comment] 2015-05-17 10:06
There isn't a Haxe 3.0.2 as far as I know (besides, flixel wouldn't even work with that), do you mean 3.2.0? And if so, is that the release or a RC?

**Comment by DrDerico** [comment] 2015-05-17 10:07
Sorry again, Haxe 3.2.0-rc.3

**Comment by Gama11** [comment] 2015-05-17 10:10
There's a rc.3? That's not listed [here](https://github.com/HaxeFoundation/haxe/tags).

Anyway, can you try with the latest version / the official release of 3.2.0? I'm not having any trouble compiling `FlxFramesCollection` here.

**Comment by DrDerico** [comment] 2015-05-17 10:12
I also hadn't any trouble, but when I called this method in my code, I've got this error :)

**Comment by Gama11** [comment] 2015-05-17 10:23
Ah, I can reproduce it now - very strange, typically compiler errors like this always happen when the file in question is compiled, regardless of whether the code in question is actually used. It can't really be due to dead-code elimination, since that's by default only enabled for the standard library.

I guess this only happens when Haxe actually tries to inline the method in question, so it has to be called at least once from somewhere. This makes it very difficult to find out if there are other functions in the codebase that have the same issue...

**Comment by DrDerico** [comment] 2015-05-17 10:25
Thank you :)

**Comment by Gama11** [comment] 2015-05-17 10:26
I haven't actually committed a fix for this yet. ;)

**Comment by Gama11** [comment] 2015-05-17 10:40
This isn't even a new issue, the same happens with Haxe 3.1.3 and probably versions earlier than that - so I doubt there are any other functions that have the same issue.

I wonder if `getIndexByName()` ever compiled, maybe Beeblerox had no-inline in the Project.xml or something like that while testing it.

**Closed** 2015-05-17 10:47 UTC
Labels: Bug
