### ISSUE TITLE
Android: master 3.3.8 placing new sound file in assets cause app crash

### ISSUE THREAD

**Issue by paala** [HaxeFlixel/flixel#1485] opened 2015-04-28 20:05 UTC
My setup:

Path to Android SDK [G:\AndroidSDK]:
Path to Android NDK [G:\AndroidNDK]:
Path to Apache Ant [G:\Apacheant]:
Path to Java JDK [C:\java6]:

C:\Users\paala>haxelib list
actuate: [1.8.3] 1.8.4
box2d: [1.2.3]
flixel-addons: [1.1.0]
flixel-tools: [1.0.5]
flixel: [3.3.8] 3.3.8 - Copy
hxcpp: [3.2.27] 3.2.81
layout: [1.2.0]
lime-samples: [2.3.0]
lime: 2.2.2 [2.3.0] 2.3.3
openfl-samples: [2.2.2]
openfl: 2.2.8 [3.0.0-beta.3] 3.0.3
swf: [1.8.6]

I tried with the latest also. same crash.

What is the working environment for 3.3.8 release?
STEPS TO REPRODUCE:
Ok,
I manage to make the problem simpler to reproduce.
1. Update everything to latest version: haxelib upgrade
2. take project jumper project test on android-> it works
3. uninstall projectjumper from device
4. paste this file: https://dl.dropboxusercontent.com/u/79341481/tittle%20game%20music.wav
into music folder.
5. compile the project again on android-> app crash 
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12412761-android-master-3-3-8-project-jumper-source-stopped-working?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by sruloart** [comment] 2015-04-28 20:17
Mode works? maybe it has something to do with the audio files and the new openFL. Also, why is your hxcpp library not set on the latest release?

**Comment by paala** [comment] 2015-04-28 20:24
I tried to set everything on latest but I found this bug. Then I set everything at latest at 28 march 2015 . Date of stable release.
Strange is that if I put first state Playstate it works.. If I comment out all in menustate it works.  then things are very unstable. If I put a trace it crashes.
I am thinking I use wrong libraries....

**Comment by MSGhero** [comment] 2015-04-28 20:39
This was fixed at some point recently in openfl and lime, upgrade everything to the latest master versions. I personally use flixel dev because there's a ton of new and fixed things there.

**Comment by sruloart** [comment] 2015-04-28 21:04
My theory is that this happen only with demos that use .wav on android (i.e, some kind of an OpenAL problem with the new OpenFL), so the solution would be to revert to openfl 2.2.8 and lime 2.1.3. 

If that doesn't work I would start deleting the existing libraries and re-installing the latest releases, maybe something got corrupted somehow.

**Comment by paala** [comment] 2015-04-29 07:28
I think I found the problem:
If I have a wav file larger that 1Mb on assets folder the project crashes no matter if I use openfl 3.0.3 or openfl 2.2.8.
Now what should I do?
Can I replace wav with ogg for all files?
I use this:
FlxG.sound.play("assets/sounds2/buttons sound" +Reg.SoundExtension , 1, false);

**Comment by sruloart** [comment] 2015-04-29 07:42
* First you can open an issue about this over the openfl/openfl repo :P
* If you strictly use mobile I can't see why not, but do you have a specific reason to use .wav or build Project Jumper at all? the only possible problem with .ogg is Flash, however....
* There's a new library (somewhere around Github) that allows for Flash to play .ogg (instead of .mp3/.wav), so even if you want to keep your sounds available for Flash this is manageable.

**Comment by paala** [comment] 2015-04-29 07:52
Hi,
I will open a bug on openfl.
I use Project jumper as my base for all projects.
I had a project build on haxeflixel 3.2.2.
i want to update to be able to upload to apple app store(64 bit requirement).

Port was ok. flash compiles ok. Now I have this problem with android

**Comment by paala** [comment] 2015-04-29 08:40
Now, with openfl 2.2.8 and lime 2.1.3 flash target has errors?
Am I the only one facing this problems?

**Comment by sruloart** [comment] 2015-04-29 09:35
I don't want to be the guy that answers a problem with "why do you even need to use it anyway?", but:
- .wav isn't mandatory to use (and like I said you can use .ogg on all targets but Flash, and on Flash it's very legal to use .mp3 instead). Just don't use it and it's problem solved. 
- You much better off making your own minimal base for games (using flixel-templates), instead of using a demo with so much unnecessary stuff. Clearly you can code, so why bother with it?
- And really, I know you don't want to, but the flixel's dev branches are the place to be if you really want to be on point with compatibility issues. It's like when you search for an old (legal) torrent: if it's old than you'll find less people that seeds it.  

About Flash, what kind of error? It's very easy to get the wrong configuration with haxelib. There's no reason that a config like this won't work on all targets (since it worked before, this is a working config AFAIK): 
- Haxe 3.1.3
- OpenFL 2.2.8
- Lime 2.1.3
- Hxcpp 3.2.27
- Flixel 3.3.6 (and not 3.3.8!)
- jdk 1.6 (android)

For all it's worth, I think that the minimal working version of Lime that supports 64 bit is 2.0.3.

**Comment by paala** [comment] 2015-04-29 13:17
Hi,
Project Jumper will be my base for creating games because with this project I started game development.
Regarding dev brach. I see the dev branch is very different than master.
I see the master as a stable release and dev as a beta that can contain bugs.
The configuration you presented works on flash and android with the major exception 

I can't use some big files no matter if I convert them to ogg or wav

**Comment by paala** [comment] 2015-04-29 13:47
To make things more funny, in project jumper the wav/ogg files works but in my project if I put the file in assets the app crashes

**Comment by sruloart** [comment] 2015-04-29 15:05
I don't think nostalgia is the way to go here, and I see dev as the most updated version of the project, so it's indeed more prone to new errors, but it's also far less buggy than the previous releases, but I'm not going to win this debate right? :)

Now that I review this thread with fresh eyes I think that your entire problem is that you don't cache the audio/music before you play it, so, in case you have a large file that isn't loaded yet to the memory, the app would simply crash when you call it. 

FlxG.sound.play() does cache the audio eventually, but in your case it's too late. What you need to do is to call FlxG.sound.cache("your audio file path") before the state (give it a while, let's say after you create your new game in Main.hx), and it should solve your problem, I think.

The funny thing is you would need to do it manually for all of your audio files manually, because cacheall() isn't implemented on 3.3.6, only on dev.

Is it a bug with the original project? well, yes. This is why you shouldn't be using it as a base :P

**Comment by paala** [comment] 2015-04-29 15:28
The problem is that the app crashes if the .wav file exists in the assets folder even if I don't call it

**Comment by paala** [comment] 2015-04-29 15:44
Regarding using dev: Dev branch changes every day.
I don't want the most updated version of the project. I just want a stable platform to build games. I had this in flixel 3.2.2 and openfl 1.2.0. Everything was working as expected. I could build on android, ios no problems.
Now I have to update to be able to submit apps (64 bit support)

**Comment by MSGhero** [comment] 2015-04-29 18:15
The problem might already be fixed on later or dev versions. Just because you are on a master version of a lib doesn't mean it works.

**Comment by sruloart** [comment] 2015-04-30 07:49
* Maybe you're trying to play an .ogg with Flash. That's not allowed by code.
* Maybe there's a problem with the embedding process. Try setting it to false (assets path="assets/sounds" rename="sounds" include="*.wav|*.mp3|*.ogg" embed=false) and then load.
* You can try using keys instead:
```xml 
assets path="assets/sounds" if="flash"
sound path="YourFile.mp3" id="YourFile" 
assets

assets path="assets/sounds" unless="flash"
sound path="YourFile.ogg" id="YourFile" 
assets
```
* I've noticed you don't have the flixel-templates library installed, so that means you've never properly setup flixel (http://haxeflixel.com/documentation/flixel-tools/), which explains why you choose to use an old demo as your template. Do setup flixel and install its templates (and flixel-demos, maybe you have an outdated version of Project Jumper to begin with) so you can do the next suggestion:
* Maybe there's a problem with the file itself, so try playing it in a basic project (cmd>`flixel template barebones -n "test"` in your chosen folder and then use FlxG.sound.play() in your PlayState) and see whether you encounter the same problem. 
* Always remember that both Android (openAL) and Flash are very susceptible to the properties of the audio file they are trying to play. In theory, you can create a .wav that won't only crash the game, but would also crash the device / browser.

**Comment by paala** [comment] 2015-04-30 11:00
Well, this bug is not at project jumper template, is at my project and my art/sound.
Original project jumper works.
Original project jumper with all the assets from my game inside -> crash even if I don't call them at all

**Comment by Tiago-Ling** [comment] 2015-04-30 11:48
Certain .wav formats may cause errors also. Check if your files are with
properties no higher than 16 bits and 44100HZ. I had trouble in the past
with 24 bit wave files.

You can use audacity to check this and re export the files if needed:
http:// <http://web.audacityteam.org>web.audacityteam.
<http://web.audacityteam.org>org <http://web.audacityteam.org>

**Comment by paala** [comment] 2015-04-30 13:36
You can try using keys instead:

assets path="assets/sounds" if="flash"
sound path="YourFile.mp3" id="YourFile" 
assets

assets path="assets/sounds" unless="flash"
sound path="YourFile.ogg" id="YourFile" 
assets

Can you be more explicit?
I want to exclude ogg from android then what should I do in project.xml and in code to play a sound in assets folder?

Thanks

**Comment by sruloart** [comment] 2015-04-30 15:07
I feel you're missing some information about the project.xml file format, read this:
http://www.openfl.org/documentation/projects/project-files/xml-format

And then continue to check these demos:
- including a specific file format without giving it an id: https://github.com/HaxeFlixel/flixel-demos/blob/7c169b80af53c7f927065b592f9c4b25eaf73beb/Performance/NeonVector/Project.xml.
- including a specific file format + giving it an id: https://github.com/HaxeFlixel/flixel-demos/blob/7c169b80af53c7f927065b592f9c4b25eaf73beb/Other/FlxPongApi/Project.xml.

**Comment by paala** [comment] 2015-04-30 18:00
The game still crashes if I convert the wav to ogg and put in project.xml:
<assets path="assets" if="flash|android" exclude="*.ogg" />

**Comment by sruloart** [comment] 2015-04-30 21:06
* Please just debug your project, we can go at it for weeks just guessing, I barely understand the problem really :)

* The problem as I understand it (as in, don't understand it): 
  - You have taken Project Jumper, added all of your unrelated assets into its assets folder, and now it won't compile on Flash. You didn't add any code to the original project.
  - Seeing this, you've decided that the problem lies with (a) large .wav file(s). This is the only possible bug (`OpenFL fails to compile to Flash whenever a big .wav file/s is/are in the assets folder`).
  - Your solution was to convert all the .wav into .ogg, and then exclude the **.wav** if="flash".
  - For some reason you got horribly confused and wrote a tag that does the opposite (excluding .ogg from Android).
  - More so, you can't actually exclude .ogg on Flash - it's already not included, by design, even if you'd wanted to.
 - Now, if you don't want/able to use those .wav files on Flash, you need to convert them to .mp3, not .ogg (which OpenFL doesn't include in Flash builds anyhow). For Android, you need to have another version converted to .ogg (because .mp3 isn't legal to use with Android). The original .wav files you should remove entirely from you assets (maybe keep a backup somewhere else if you want to). 
  - i.e. you don't need to use exclude or anything like it in order to solve the problem.

**Comment by paala** [comment] 2015-05-01 06:02
Hello,
I can't just debug, when the game crashes nothing is shown in logcat.
The whole story is as I presented and I will present it again.
I have a game(Hero Quest) made 1 year ago with haxe 3.0.3 openfl 1.2.0 and haxeflixel 3.2.2.
With this setup everything worked on flash , android and ios. But I cannot submit to appstore because of 64 bit requirement.
I updated the project to latest versions, (or haxeflixel 3.3.6, openfl 2.2.8 lime 2.1.3).
Flash works OK.
When I compile to android game crashed on device , compile is ok.
Then I made some tests.
I take project jumper. game works on android.
I take project jumper and put all my art and sound folders inside the project, no code changes-> game crash on android.
I can't share all my art and sound folder here to test, but I will try to get a minimal version that crash the game on android.

**Comment by paala** [comment] 2015-05-01 14:18
Ok, 
I manage to make the problem simpler to reproduce.
1. Update everything to latest version: haxelib upgrade
2. take project jumper project test on android-> it works
3. uninstall projectjumper from device
4. paste this file: https://dl.dropboxusercontent.com/u/79341481/tittle%20game%20music.wav
into music folder.
5. compile the project again on android-> app crash

**Comment by Tiago-Ling** [comment] 2015-05-01 14:33
The file did run perfectly here on Android, using:

   - Haxe 3.1.3;
   - Lime 2.3.0;
   - OpenFL 3.0.0-Beta.3
   - Haxeflixel development version.

The one thing i changed was removing the spaces from the file name.

**Comment by paala** [comment] 2015-05-01 14:39
I made some tests on former openfl versions this bug happens if I have other art in art folder. Anyway I am using all latest.  This bug occurs from openfl 1.4  to openfl 3.0.3. The only solution to develop on android is to go on haxe 3.0.1 and haxeflixel 3.2.2

**Comment by Tiago-Ling** [comment] 2015-05-01 15:02
That's the thing: this bug did not happen to me using your audio file.

Running perfectly fine in Flash, Neko, Windows, Android.

I included your file in my current project, which has around ~100MB of art
assets, a lot of them being loaded in the State while i played your file,
both as common sound (FlxG.sound.play) and as a looping music
(FlxG.sound.playMusic).

I also created a "ProjectJumper" project and run it with your file -
everything works fine for all targets. Didn't test Android because that
would demand a lot of changes to ProjectJumper's code, but i'm sure if i
did the file and project would run just fine.

I'm actively developing for Android target using the library versions i
wrote in the last post with no problems regarding audio - it's very
probable your problem is related to other things: old / low memory
hardware, trying to load a lot of stuff into memory at once.

If you really think this is a problem with HaxeFlixel you must provide more
info on it - ideally the Android call stack from the application crash.

I suggest you try to follow the instructions here to keep a log of the
Android application:

http://www.openfl.org/archive/community/installing-openfl/how-can-we-debug-android-app/

Do this and look for the word "error" in the log.

**Comment by paala** [comment] 2015-05-01 15:11
from logcat:

05-01 18:09:42.779: A/libc(552): Fatal signal 11 (SIGSEGV) at 0x7883efc8 (code=2), thread 570 (Thread-11302)

**Comment by Tiago-Ling** [comment] 2015-05-01 15:14
Please link the full log into [Pastebin](http://pastebin.com/)

**Comment by paala** [comment] 2015-05-01 15:26
Here you go:
http://pastebin.com/PLv8KsEY

**Comment by Tiago-Ling** [comment] 2015-05-01 16:52
Alright, i couldn't discover anything useful by looking at the log. There's a program which can transform it into a more readable stuff which is ndk-stack (usage here: http://stackoverflow.com/questions/18436383/how-to-check-crash-log-using-android-ndk-in-cocos2d-x)

However, i did downgrade my `flixel` and `flixel-demos` to versions `3.3.8` and `1.1.1` respectively, created a new project jumper demo, put your unaltered audio file in it (using `FlxG.sound.playMusic`) and compiled the project for android-release.

The demo runs without crashing and your audio file plays and loops as expected. However the game in unplayable because the only thing that appears on the screen is this:

https://dl.dropboxusercontent.com/u/18504814/Screenshot_2015-05-01-13-27-29.png

Probably because this demo was not supposed to run on Android - or the flixel version is too old to be 100% compatible with the new OpenFL and Lime versions.

I did run this demo on Android (using a One PlusOne) using the following library versions:
* Haxe 3.1.3;
* Lime 2.3.3;
* Hxcpp 3.2.37;
* OpenFL 3.0.3;
* Flixel 3.3.8;
* Flixel-demos 1.1.1.

So at least here the demo runs and plays your file - the problem must lie elsewhere. 

From my past experience this **sounds like a memory problem**: when you try to allocate something the application crashes, that's what i could tell from your log file.

This could also be some weird problem related to hardware - what device are you using?

After testing it here with the master version of HaxeFlixel it does not seem to be a bug in the framework - probably something on your side since the steps you provided cannot reproduce the problem.

I'd suggest for you to remove assets, one by one (starting with the biggest ones) and seeing if the application works. If by removing a combination of assets your game runs, it might be a memory problem.

**Comment by paala** [comment] 2015-05-01 18:27
Hi,
The demo was tested on my samsung s3. I tested on other s4 phone and it works. however the whole project doesn't work either on s3 or s4.
If there is a memory problem , what can it be? in haxe 3.0.1 it worked. How can an asset can crash the game? This is a severe bug somewhere.

**Comment by paala** [comment] 2015-05-01 19:31
I tested bunny mark from openfl and crash .

**Comment by Gama11** [comment] 2015-05-23 15:37
Closing this as it seems to be an OpenFL issue.

**Closed** 2015-05-23 15:37 UTC
