### ISSUE TITLE
Weird thing when haxelib run flixel-tools setup

### ISSUE THREAD

**Issue by yugiohatemu** [HaxeFlixel/flixel#1661] opened 2015-11-19 01:45 UTC
Hi, I have a weird issue when trying to run "haxelib run flixel-tools setup" according to the tutorial. I had haxe for a long time but I do a reinstall so I started everything from scratch today. ie. using latest haxe and such

>Do you want to set up the command alias 'flixel' to 'haxelib run flixel-tools'?
A simple flixel script will be added to your /usr/bin/ [y/n]?
y
cp: /usr/lib/haxe/flixel: No such file or directory
chmod: /usr/lib/haxe/flixel: No such file or directory
ln: /usr/bin/flixel: File exists
...
....
Called from ? line 1
Called from FlxTools.hx line 128
Called from FlxTools.hx line 14
Called from a C function
Called from FlxTools.hx line 71
Called from massive/sys/cmd/CommandLineRunner.hx line 109
Called from massive/sys/cmd/CommandLineRunner.hx line 258
Called from commands/SetupCommand.hx line 28
Called from commands/SetupCommand.hx line 206
Called from utils/CommandUtils.hx line 387
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 38
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/io/File.hx line 54
Uncaught exception - [file_open,/usr/lib/haxelib/flixel-tools/1,1,1/settings.json]

I double check because haxe doesnt seem to create a haxe directory under /usr/lib/haxe, and it seems the script should maps to */usr/lib/haxelib* instead of */usr/lib/haxe* since flixel lives under haxelib. Anyway, I just did a simple work around, ie. 

>alias flixel="haxelib run flixel-tools"

I am on latest OSX el capion.

**Comment by caiges** [comment] 2015-12-16 04:26
Ran into this myself, I'm just getting into haxe and haven't determined which code is running when using the "setup" command for flixel-tools. Your workaround is sufficient for me as well.

**Comment by caiges** [comment] 2015-12-16 04:31
In case you're curious I ran `haxelib config flixel-tools` to get info on the location of flixel-tools:
```bash
haxelib config flixel-tools
/usr/local/Cellar/haxe/3.2.1/lib/haxe/lib/
```
You can symlink the appropriate scripts to `/usr/local/bin` (or whatever path you'd like) to get it to work properly. `flixel`, for example:

```bash
ln -s /usr/local/Cellar/haxe/3.2.1/lib/haxe/lib/flixel-tools/1,1,1/bin/flixel.sh /usr/local/bin/flixel
```

**Comment by Gama11** [comment] 2015-12-16 07:52
There are two open pull requests with fixes, but I can't really test them myself...

- HaxeFlixel/flixel-tools#60
- HaxeFlixel/flixel-tools#61

**Comment by Gama11** [comment] 2015-12-17 20:51
Closing this as it's the wrong repo / a duplicate of HaxeFlixel/flixel-tools#59.

**Closed by Gama11** 2015-12-17 20:51 UTC
