### ISSUE TITLE
Runtime manipulation of objects using the mouse

### ISSUE THREAD

**Issue by Dovyski** [HaxeFlixel/flixel#1832] opened 2016-04-23 17:58 UTC
Hey there!

A while ago I was working on a feature for Flixel Community which was called "interactive debug". There is a complete description of the whole thing in this [blog post](http://www.as3gamegears.com/blog/interactive-debug-in-flixel-community/). The general idea is to allow developers to manipulate anything on the screen (add/remove tiles, move/delete sprites, etc) while the game is running, as demonstrated below:
 
![flixelcommunity-interactivedebug-delete](https://cloud.githubusercontent.com/assets/512405/14763127/f90e5dd6-098c-11e6-8345-60b45ba15ba4.gif)

It's quite useful for quickly tweaking things of a game during development. My overall goal for this in Flixel Community was to evolve the implementation until the point where the engine would feature an "in-game editor" that could be used to create (saving, loading, etc) levels, scenes, effects, etc.

If you guys like the idea, I would love to port that code from Flixel Community to HaxeFlixel :)

**Comment by IBwWG** [comment] 2016-04-23 18:03
I totally love this.  I ended up writing the same thing for my own project, but only for positioning and resizing speech bubbles.  I had planned to release it after releasing my game, which hasn't happened yet.  A generic one would certainly kick ass, and I'm sure my speech bubbly thingie could integrate with it somehow as an add-on.  Or it could stand alone, who cares.

**Comment by Gama11** [comment] 2016-04-23 18:08
The debugger has changed quite a bit in HaxeFlixel, so it probably makes sense to adjust things a bit.

I guess this is a duplicate of #972. But yes, I like the idea, according to the date on that issue, I've been wanting to do this for two years.

**Closed by Gama11** 2016-04-23 18:08 UTC

**Comment by Dovyski** [comment] 2016-04-23 18:25
> according to the date on that issue, I've been wanting to do this for two years.

It makes us two then :smile:  I will catch up on the discussion at #972 then.
