### ISSUE TITLE
FlxBackdrop is not aware of the camera's view rect

### ISSUE THREAD

**Issue by DengerGithub** [HaxeFlixel/flixel#2649] opened 2022-10-06 01:59 UTC
uhhh, i have a error with flxbackdrop, the backdrop just bugges and some parts disapears and makes it visibles again, idk how to explain it lol. here's a example, i hope you guys can help me.	

```hx
coolFlxBackdrop = new FlxBackdrop(Paths.image('Fake_Popups/random1'), 0, 0, true, true, 100, 50);
coolFlxBackdrop.screenCenter();
coolFlxBackdrop.velocity.set(50, 100);
coolFlxBackdrop.visible = false;
coolFlxBackdrop.antialiasing = true;
coolFlxBackdrop.alpha = 0.6;
coolFlxBackdrop.x = -700;
add(coolFlxBackdrop);
```

https://user-images.githubusercontent.com/89358737/194197443-8e56c8f2-e843-4156-b6cf-9fb7f3bc74e8.mp4

**Comment by MemeHoovy** [comment] 2022-10-06 02:00
this is not the place to put this issue

**Comment by DengerGithub** [comment] 2022-10-06 02:00
why?

**Comment by MemeHoovy** [comment] 2022-10-06 02:01
this is for haxeflixel, not fnf

**Comment by DengerGithub** [comment] 2022-10-06 02:02
I know, but haxeflixel works on fnf, why this can be bad? I dont see any issue.

**Comment by MemeHoovy** [comment] 2022-10-06 02:03
because this is where you submit issues for FLIXEL, not FNF

**Comment by MemeHoovy** [comment] 2022-10-06 02:03
close this and submit it in the proper repo

**Comment by MemeHoovy** [comment] 2022-10-06 02:05
okay, but still

**Comment by DengerGithub** [comment] 2022-10-06 02:05
Also how did you just replied me like, 10 seconds ago? LMAO

**Comment by MemeHoovy** [comment] 2022-10-06 02:06
shut

**Comment by DengerGithub** [comment] 2022-10-06 02:06
uh oh, he angered :sob:

**Comment by MemeHoovy** [comment] 2022-10-06 02:09
whatever then🙄

**Comment by DengerGithub** [comment] 2022-10-06 02:10
can you just..leave posting shit on this issue?

**Comment by DengerGithub** [comment] 2022-10-06 02:13
yeah idm

**Comment by Geokureli** [comment] 2022-10-06 03:12
> this is for haxeflixel, not fnf

They are pointing out a vlaid Haxeflixel issue, please leave the moderation to the maintainers.

@DengerGithub I'll look into this, thanks

**Comment by MemeHoovy** [comment] 2022-10-06 03:16
> > this is for haxeflixel, not fnf
> 
> They are pointing out a vlaid Haxeflixel issue, please leave the moderation to the maintainers.
> 
> @DengerGithub I'll look into this, can you attach the backdrop image you're using, and let me know what flixel/haxe/lime/openfl versions you're using? Thanks
> 
> Also what size is your game? same as FNF?

🤷🏻‍♂️

**Comment by Geokureli** [comment] 2022-10-06 03:21
> 🤷🏻‍♂️ I don't know what you consider valid at this point, or what you consider was valid to begin with

This is an issue with `FlxBackdrop`, a class in `flixel-addons`, not some FNF utility class. They are using it in a reasonable and expected way and getting unexpected results. I think it may be happening because of some changes I made to FlxSprite's getScreenPosition. That's why this is valid. If it wasn't I'll let them know why and where they should go for help.

**Comment by MemeHoovy** [comment] 2022-10-06 03:23
alright, good to know

**Comment by Geokureli** [comment] 2022-10-06 03:24
I wish instead of deleting both your flame posts, I edited them to be very friendly compliments about each other.

**Comment by MemeHoovy** [comment] 2022-10-06 03:24
> I wish instead of deleting both your flame posts, I edited them to be very friendly compliments about each other.

you'd wish

**Comment by DengerGithub** [comment] 2022-10-06 04:07
Okay, so, now im not on my pc, maybe tomorrow i can give you the image and send you the openfl ver!

**Comment by DengerGithub** [comment] 2022-10-06 17:49
Hi @Geokureli ! So...The OpenFL version is the last one, and the size of the game is 640x488, the image is this, also, the bug happened on 1080x720 game sizes too.

[random1](https://user-images.githubusercontent.com/89358737/194383539-81c9eea8-3594-4bb5-912e-d12b3340411e.png)

**Comment by DengerGithub** [comment] 2022-10-06 17:50
![random1](https://user-images.githubusercontent.com/89358737/194383711-aca27691-bdba-4fd0-af7a-f3ba47ec5f25.png)

**Comment by Geokureli** [comment] 2022-10-12 16:25
@DengerGithub 
I tried recreating this from your snippet but didn't see the issue. does it happen right away or does it start to happen after playing for a while? is it seemingly random when it starts to happen or is it reliable? is this happening on windows or hashlink? does it happen on all targets?

I'm trying to create a small project that reproduces this issue, but I'm having trouble. If you take the relevant code and create a new project or test state does it still happen to you? if not, it may be due to some other code in your project. Try as hard as you can to make a tiny, isolated example that reliably causes this issue, otherwise I won't be able to diagnose the problem.

**Comment by DengerGithub** [comment] 2022-10-27 20:54
It is fixed? Thanks you so much :)

**Comment by DengerGithub** [comment] 2022-10-27 20:56
Oh, i didnt readed the up message, so..
I think thve issue happends because the FlxCamera focus thingy

**Comment by DengerGithub** [comment] 2022-10-27 21:02
Im not on my pc now, but i'll test it later c:

**Comment by DengerGithub** [comment] 2022-10-27 21:02
Woops, accidentaly closed

**Comment by DengerGithub** [comment] 2022-10-27 21:20
It doesnt work :c, i updated flixel-addons and nothing, i need to restart the pc?

**Comment by DengerGithub** [comment] 2022-10-27 21:21
oh, wait, im gonna do the backdrop.camZoom = 0.5; thingy

**Comment by DengerGithub** [comment] 2022-10-27 21:25
Wait, i think flxbackdrop didnt updated

**Comment by DengerGithub** [comment] 2022-10-27 21:36
Btw, i tried on windows

**Comment by Geokureli** [comment] 2022-10-28 01:26
> Btw, i tried on windows

you tried my new branch? did it work?

**Comment by DengerGithub** [comment] 2022-10-28 05:23
Ngl i updated it on haxelib, but it doesnt work.
Should i need to reinstall it?

**Comment by Geokureli** [comment] 2022-10-28 13:34
no, it's not released yet

try adding this to your project and using that
https://gist.github.com/Geokureli/d28b094aa26cf305169846becdfc44da

**Comment by DengerGithub** [comment] 2022-10-28 17:52
Sure :)

**Comment by DengerGithub** [comment] 2022-10-28 17:55
I can try later because im kinda busy rn

**Comment by DengerGithub** [comment] 2022-10-28 19:39
Huh, this is weird, it doesnt work.
I kinda changed the code and it keeps happening
Should i use the normal way to use the flxbackdrop?
Like, without the `velocity.set` thing
![imagen](https://user-images.githubusercontent.com/89358737/198718666-6bdf0bf2-400f-4027-a0ea-aa084f9ccd2d.png)


https://user-images.githubusercontent.com/89358737/198718513-858a9233-009c-40f1-a8bd-e3e2e9381817.mp4

**Comment by DengerGithub** [comment] 2022-10-28 19:40
Wait, the video doesnt work

**Comment by DengerGithub** [comment] 2022-10-28 19:41
https://user-images.githubusercontent.com/89358737/198719078-0d3973bc-99fe-4261-b1d9-f2ccc76213cc.mp4

**Comment by DengerGithub** [comment] 2022-10-28 19:45
Btw, with that, i need to haxelib update? or i need to restart the pc

**Comment by DengerGithub** [comment] 2022-10-28 19:53
WAITWAIT
i forgoted to delete the "2" from the flxbackdrop class thingy
![imagen](https://user-images.githubusercontent.com/89358737/198721183-fcf53024-e0f8-4749-9654-e1f6e07c3216.png)

**Comment by DengerGithub** [comment] 2022-10-28 19:56
nvm, still doesnt work :c

**Comment by DengerGithub** [comment] 2022-10-28 20:09
I needed to replace the FlxBackdrop code with the FlxBackdrop2 code?

**Comment by Geokureli** [comment] 2022-10-29 16:07
I updated the gist to work with flixel 4.11, just create a new class in your project called FlxBackdrop2, paste this in there, and change the package at the top to match the location of the class in your project
https://gist.github.com/Geokureli/d28b094aa26cf305169846becdfc44da

**Comment by DengerGithub** [comment] 2022-10-29 16:50
IT WORKS! Thanks you so much :), i admire how good are you coding btw

https://user-images.githubusercontent.com/89358737/198843487-2df796b7-3eba-4008-b507-75540b0c4e75.mp4

**Closed** 2022-10-29 16:56 UTC

**Comment by Geokureli** [comment] 2022-10-29 18:19
Thanks!
