### ISSUE TITLE
FlxTimer reset/start inconsistency

### ISSUE THREAD

**Issue by l0rb** [HaxeFlixel/flixel#2230] opened 2019-08-20 16:26 UTC
Currently FlxTimer has a `start()` and a `reset()` method which behave inconsistent in regards to their first argument. imho it's dubious to accept negative time arguments at all, but for reset all negative values are the same as not passing in anything at all. If the community agrees that the behaviour should change I'll happily create a PR that replaces the default value of `reset()`s argument with null to keep it optional, and handles negative values the same as `start()` does.
```haxe
timer = new FlxTimer();
timer.start(5); // triggers at 5 seconds
timer.reset(3); // now triggers at 3 seconds
timer.start(-5); // triggers at 5 seconds
timer.reset(-3); // now triggers at 5 seconds again <- this one is weird
timer.reset(); // triggers at 5 seconds
```

**Comment by Geokureli** [comment] 2019-10-09 18:53
This is by design, the default value of `reset()`'s arg is -1, which is commonly used as the `null` state of an integer. To me this is perfectly fine

https://github.com/HaxeFlixel/flixel/blob/dev/flixel/util/FlxTimer.hx#L142

I don't mind that reset handles negative values different than start, but I do think that start should react by either throwing an error or changing it to zero.

**Comment by bhgsbatista** [comment] 2020-08-27 03:31
@Geokureli are you on the haxe discord? https://discordapp.com/invite/rqEBAgF

@Gama11 lets close this as by design.

**Closed** 2020-08-27 06:28 UTC
