### ISSUE TITLE
FlxSprite and alpha tweening breaks translucency on html5 target (flixel dev)

### ISSUE THREAD

**Issue by Tw1ddle** [HaxeFlixel/flixel#1576] opened 2015-07-25 22:21 UTC
Sprites are rendered opaque when alpha is changed/updated more than once on html5. Here's an example that should show an opaque red square with a translucent blue square on top of it, where the blue square should gradually tween from almost-transparent to opaque:

```
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.tweens.FlxTween;
import flixel.util.FlxColor;

class Minimal extends FlxState {	
	override public function create():Void {
		super.create();
		
		var opaqueRectangle = new FlxSprite();
		var translucentSquare = new FlxSprite();
		
		opaqueRectangle.makeGraphic(FlxG.width, 100, FlxColor.RED);
		translucentSquare.makeGraphic(200, 300, FlxColor.BLUE);
		
		opaqueRectangle.screenCenter();
		translucentSquare.screenCenter();
		
		opaqueRectangle.alpha = 1.0;
		translucentSquare.alpha = 0.1; // Almost-transparent square
		
		FlxTween.tween(translucentSquare, { alpha: 0.8 }, 4); // Comment this out and the blue square will be translucent on html5...
		FlxTween.tween(translucentSquare, { x: FlxG.width / 2 + 200 }, 10); // A position tween works as expected, so it's not just that tweens are broken on html5...
		
		add(opaqueRectangle);
		add(translucentSquare);
	}
}
```

Blue square is rendered incorrectly/opaque on html5:

<img width="531" alt="screenshot_77" src="https://cloud.githubusercontent.com/assets/1332318/8891470/32103ea6-3323-11e5-819a-9ecc5b3b8ed5.png">

It should be translucent and slowly tween to almost-opaque, as it does on Flash:

<img width="612" alt="screenshot_76" src="https://cloud.githubusercontent.com/assets/1332318/8891467/1cbe4b42-3323-11e5-9894-b6ab622cc468.png">

Here are my haxelibs:
```
flixel-addons: git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel: git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]
hxcpp: [3.2.102]
lime: [2.5.2]
openfl: [3.2.2]
swf: [1.9.1]
```

Any ideas?

**Comment by Tw1ddle** [comment] 2015-07-25 23:04
Narrowed this down a bit. Sprites are rendered correctly/translucent when alpha is set just once, but if the alpha is set again the sprite is rendered opaque, no matter what the alpha is set to subsequently. So I suppose it's likely to be a rendering issue?

**Comment by sruloart** [comment] 2015-07-26 00:16
I don't know if that's related or not, but I had weird issues with color in html5 with the latests Lime/OpenFL. Sometimes a color would simply not show, be that the background color of the camera or a simple sprite graphic (via the makeGraphic). What happens if you try a .png?

**Comment by Tw1ddle** [comment] 2015-07-26 01:37
@sruloart Same situation when using .pngs.

I notice that ```lime.graphics.utils.ImageDataUtil.colorTransform``` is called when the color transform/alpha changes. It loops over the pixels once per image, but returns early without doing anything when the alpha is changed subsequently. The difference between platforms is that ```image.buffer.data``` is null in colorTransform on html5 after the first call, whereas it isn't null on the neko or cpp targets. Maybe that's pointing towards the problem...

**Comment by Gama11** [comment] 2015-07-28 20:01
Closing as this seems to be a Lime issue (see https://github.com/openfl/lime/issues/520).

**Closed by Gama11** 2015-07-28 20:01 UTC

**Comment by jgranick** [comment] 2017-01-09 22:57
Hey guys,

I believe this was resolved, but if it has not been, please let me know and then we can see if we can identify a test case to reproduce. Thanks a bunch :wink:
