### ISSUE TITLE
FlxG.switchstate doesnt remove ogmo map from background html5

### ISSUE THREAD

**Issue by dumasymptote** [HaxeFlixel/flixel#2098] opened 2017-07-20 17:08 UTC
- **Haxe version:** 3.4.2
- **Flixel version:** 4.2.1
- **OpenFL version:** OpenFL Command-Line Tools (3.6.1-LQBZc4)
- **Lime version:** (2.9.1)
- **Affected targets:**
HTML5 - possibly others but it works with neko
________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.text.FlxText;
import flixel.FlxG;
import flixel.addons.editors.ogmo.FlxOgmoLoader;
import flixel.tile.FlxTilemap;
import flixel.FlxObject;
import flixel.FlxCamera;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	private var txtTitle:FlxText;
	private var player:Player;
	private var map:FlxOgmoLoader;
	private var mapWalls:FlxTilemap;
	private var hud:HUD;
	private var uiCam:FlxCamera;
	private var playerCam:FlxCamera;
	private var exits:FlxTypedGroup<Exit>;

	override public function create():Void
	{

		uiCam = new FlxCamera(0, 0, FlxG.width, Math.floor(FlxG.height/20));
		playerCam = new FlxCamera(0,Math.floor(FlxG.height/20), FlxG.width,  FlxG.height - Math.floor(FlxG.height/20));
		playerCam.zoom = 2;

		map = new FlxOgmoLoader("assets/data/level-001.oel");
		mapWalls = map.loadTilemap(AssetPaths.tileset__png, 16,16, "Tiles");
		mapWalls.follow(playerCam);
		mapWalls.setTileProperties(1, FlxObject.ANY,54);
		mapWalls.setTileProperties(56, FlxObject.NONE,5);
		add(mapWalls);
		

		txtTitle = new FlxText(20,0,0,"Play State Test", 22);
        txtTitle.alignment = CENTER;
        txtTitle.screenCenter(X);
        add(txtTitle);

		exits = new FlxTypedGroup<Exit>();
		add(exits);

		player = new Player();
		map.loadEntities(placeEntities, "Hero");
		add(player);

		// to do add a second camera that focuses on the UI so that it isnt affected by the zoom.
		hud = new HUD(player.hp, player.maxHp, player.mp, player.maxMp, player.exp, player.lvl);
		add(hud);

		
		playerCam.follow(player, TOPDOWN, 1);
		FlxG.cameras.reset(uiCam);
		FlxG.cameras.add(playerCam);

		super.create();
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		FlxG.collide(player, mapWalls);
		FlxG.overlap(player, exits, playerExit);
	}

	private function placeEntities(entityName:String, entityData:Xml):Void
	{
		var x:Int = Std.parseInt(entityData.get("x"));
		var y:Int = Std.parseInt(entityData.get("y"));

		switch (entityName)
		{
			case "Hero" : 
				player.x = x;
				player.y = y;
			case "exit" :
				exits.add(new Exit(x, y, Std.parseInt(entityData.get("nxtLevel"))));
		}
	}
	private function playerExit(p:Player, e:Exit):Void
	{
		FlxG.switchState(new TransitionState(e.get_nxtLevel()));
	}
}

package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.text.FlxText;
import flixel.ui.FlxButton;
import flixel.util.FlxAxes;
import flixel.util.FlxColor;
import flixel.util.FlxSave;
import flixel.FlxCamera;

class TransitionState extends FlxState
{
    public var lvlTrans(get, null):Int;
    private var txtTitle:FlxText;
    private var transitionCam:FlxCamera;
    
    public function new(lvl:Int)
    {
        lvlTrans = lvl;
        super();
    }
    override public function create():Void
    {       
        transitionCam = new FlxCamera(0,0,FlxG.width, FlxG.height, 1);
        FlxG.cameras.reset(transitionCam);
        txtTitle = new FlxText(0,Std.int(FlxG.height/2),0,"Transition Test: Lvl "  + lvlTrans);
        txtTitle.alignment = CENTER;
        txtTitle.screenCenter(FlxAxes.X);
        add(txtTitle);
    }
    public function get_lvlTrans():Int
    {
        return this.lvlTrans;
    }
}

________________________________

**Observed behavior:**
The state switches to the new state but the tilemap still shows behind objects on the new state
**Expected behavior:**
The new state should start as a blank slate for adding stuff too.

**Comment by dumasymptote** [comment] 2017-07-20 17:17
if you need a project to check this i have the files and everything here 

https://github.com/dumasymptote/codeNameSkulls

**Comment by Gama11** [comment] 2017-07-20 19:49
To clarify - when you complete the first level and get to the "Transition Test: Lvl 2" text, the map is still visible?

If so, I can't reproduce that (HTML5):

![](http://i.imgur.com/FCh03TW.png)

**Comment by dumasymptote** [comment] 2017-07-20 19:59
This is what it looks like on my machine running this in chrome. As you can see the screen doesn't redraw. This is with chrome Version 59.0.3071.115 which is the latest 64 bit version.

![image](https://user-images.githubusercontent.com/652095/28436241-d110e554-6d5b-11e7-8dac-fce62033b772.png)

**Comment by Gama11** [comment] 2017-07-20 20:03
Interesting, when I downgrade to Flixel 4.2.1, I can reproduce. This must have been fixed by something in the meantime. :)

Can you try with a dev version of Flixel and verify?

```
haxelib git flixel https://github.com/HaxeFlixel/flixel
```

**Comment by dumasymptote** [comment] 2017-07-20 20:12
Yea it looks like if I use the dev version of Flixel it works as intended.

**Comment by Gama11** [comment] 2017-07-20 20:43
Great. :)

**Closed by Gama11** 2017-07-20 20:43 UTC
