### ISSUE TITLE
FlxSpriteGroup performs slow

### ISSUE THREAD

**Issue by SomeGuyWhoLovesCoding** [HaxeFlixel/flixel#3020] opened 2024-01-30 04:50 UTC
- **Haxe version:** 4.2.5
- **Flixel version:** 5.2.2
- **OpenFL version:** 9.0.2
- **Lime version:** ?.?.?
- **Affected targets:** N/A
________________________________
(Some details because why not) I know FlxSpriteGroup's suck because of how it performs. I know a FlxTypedGroup<FlxSprite> does fine but a FlxSpriteGroup doesn't do better than it. The FlxSpriteGroup has a group variable with the type "FlxTypedGroup<T>" because they wanted to make it so that it actually adds onto a FlxState, so they made the FlxSpriteGroup extend FlxSprite. How it updates and draws is pretty slow imo.

**Observed behavior:**
The FlxSpriteGroup renders slower right off the bat.
**Expected behavior:**
I expected FlxSpriteGroup to run well.

**Comment by EyeDaleHim** [comment] 2024-01-30 04:54
I don't think this is a very good way to describe "performs" slow.

What's so slow about it? What's the actual issue? Please make sure your Issue makes sense before you waste time.

**Comment by SomeGuyWhoLovesCoding** [comment] 2024-01-30 04:58
> I don't think this is a very good way to describe "performs" slow.
> 
> What's so slow about it? What's the actual issue? Please make sure your Issue makes sense before you waste time.

The issue is that FlxSpriteGroup uses a FlxTypedGroup variable and the class itself contains every FlxTypedGroup function. Also it extends FlxSprite and it's pretty obvious how ridiculous code performs, FlxSpriteGroup's suck 😑

**Comment by SomeGuyWhoLovesCoding** [comment] 2024-01-30 05:08
> > The issue is that FlxSpriteGroup uses a FlxTypedGroup variable and the class itself contains every FlxTypedGroup function. Also it extends FlxSprite and it's pretty obvious how ridiculous code performs, FlxSpriteGroup's suck 😑
> 
> Please edit your Issue to include additional information like this one.

I just did

**Comment by Rudyrue** [comment] 2024-01-30 07:39
> > I don't think this is a very good way to describe "performs" slow.
> > What's so slow about it? What's the actual issue? Please make sure your Issue makes sense before you waste time.
> 
> The issue is that FlxSpriteGroup uses a FlxTypedGroup variable and the class itself contains every FlxTypedGroup function. Also it extends FlxSprite and it's pretty obvious how ridiculous code performs, FlxSpriteGroup's suck 😑

that doesn't cause sprite groups to run bad
again, like i showed in the haxe discord server
sprite groups do NOT run bad, you have to try really hard for them to run horribly
also, the draw method is not horrible :sob:
it just does a for loop over every alive object in the group
you literally cannot do anything about that

it's either you wrote code that is so bad that the performance is noticable and you're just blaming your issues on something else or you just have a bad pc

**Comment by Raltyro** [comment] 2024-01-30 07:41
It's mostly because one of your codes that runs slow

**Comment by SomeGuyWhoLovesCoding** [comment] 2024-01-30 14:01
> > > I don't think this is a very good way to describe "performs" slow.
> > > What's so slow about it? What's the actual issue? Please make sure your Issue makes sense before you waste time.
> > 
> > 
> > The issue is that FlxSpriteGroup uses a FlxTypedGroup variable and the class itself contains every FlxTypedGroup function. Also it extends FlxSprite and it's pretty obvious how ridiculous code performs, FlxSpriteGroup's suck 😑
> 
> that doesn't cause sprite groups to run bad again, like i showed in the haxe discord server sprite groups do NOT run bad, you have to try really hard for them to run horribly also, the draw method is not horrible 😭 it just does a for loop over every alive object in the group you literally cannot do anything about that
> 
> it's either you wrote code that is so bad that the performance is noticable and you're just blaming your issues on something else or you just have a bad pc

I have a decent pc

**Comment by Geokureli** [comment] 2024-01-30 17:35
Just going to bring this up again: [#3005 - FlxDrawQuadsItem and FlxDrawTrianglesItem are unoptimized](https://github.com/HaxeFlixel/flixel/issues/3005), where you're changes were determined to be slower and broke various features. I can also tell from your responses in this thread that you system for measuring performance is not very scientific, I'm pretty sure you're just running your game and trying to "notice" performance issues. In discord you've shown alternatives that were demonstrably slower.

If you want me to take this seriously, you need to create a small test case that shows off the difference in performance between the current FlxSpriteGroup and your proposal, so that other people may reproduce the findings. This should be a small but complete test. don't just show the class you keep posting in discord, show a test state that uses it, and how you are measuring performance in this state.

**Comment by Geokureli** [comment] 2024-02-12 18:17
closing until something substantial is presented

**Closed by Geokureli** 2024-02-12 18:17 UTC
