### ISSUE TITLE
FlxCamera bgColor of 0x0 causes black screen on Next

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1793] opened 2016-03-29 20:37 UTC
see https://groups.google.com/d/msg/haxeflixel/O6x4KconHcs/ElcZO8d9AAAJ

```xml
<set name="next" />
```

```haxe
FlxG.cameras.bgColor = 0x0;
```

Probably an OpenFL bug, but still gotta isolate and report it (and maybe find a workaround).

**Comment by JoeCreates** [comment] 2016-04-07 23:28
I've narrowed it down. I can confirm it is only on Next.

https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxCamera.hx#L1255

Commenting this out fixes it. A drawRect call (size/color doesn't matter) will mean the graphic renders as normal. Without it, the graphic is blank.

It seems this should be reported on OpenFL, but a workaround for Flixel for now can simply be to not skip the fill if the alpha is 0.

**Comment by larsiusprime** [comment] 2016-04-07 23:36
Is this your bug @SeiferTim ?

**Comment by SeiferTim** [comment] 2016-04-08 14:16
Sounds like it: I have some special code that adds tiles to my Stage's background. In next, recently, no matter what I set my `bgColor` to, it's transparent, and I can see my tiles behind the background (When it used to be opaque - and still is in flash)

**Comment by SeiferTim** [comment] 2016-04-08 14:20
@JoeCreates if you set your window color (in `Project.xml`) to non-black, does your `bgColor` appear to be that color?

**Comment by JoeCreates** [comment] 2016-04-08 15:05
@SeiferTim I haven't checked, but it's already obvious to me that it's transparent because I had a camera that was rendering behind the camera that wasn't. I wasn;t getting the black screen as described in the issue, I was just not seeing my uiCamera which I had set to have a transparent background. The world camera rendered fine, but then that one was being filled with a non transparent background color each frame.

**Comment by SeiferTim** [comment] 2016-04-08 15:07
I'm pretty sure this is an OpenFL/Lime issue, since it wasn't happening until I switched to the `development` version of both.

**Comment by larsiusprime** [comment] 2016-04-08 17:06
Are the ```master``` branches behaving better?

**Comment by Beeblerox** [comment] 2016-04-16 08:40
please try this one (but don't know will it help):
replace the line 1260 in FlxCamera:
`targetGraphics.beginFill(Color, FxAlpha);`
with
`targetGraphics.beginFill(Color.to24Bit(), FxAlpha);`

**Comment by Gama11** [comment] 2016-04-16 10:09
Doesn't make a difference - would be surprised if it did, since line 203 in `CameraFrontEnd` already converts the color to 24 bit:

```haxe
camera.fill(camera.bgColor.to24Bit(), camera.useBgAlphaBlending, camera.bgColor.alphaFloat);
```

**Comment by Beeblerox** [comment] 2016-04-16 10:23
@Gama11 oh, totally missed that. So it's an openfl ussue then for sure

**Comment by Beeblerox** [comment] 2016-04-16 10:24
We can only add bgSprite rendering in FlxState then, until it's not fixed there

**Comment by Gama11** [comment] 2016-04-16 10:31
For that to happen the issue first has to be reported. :)

**Comment by JoeCreates** [comment] 2016-09-07 19:04
Thought I'd just update my comment and say its now https://github.com/HaxeFlixel/flixel/blob/dev/flixel/FlxCamera.hx#L1358. I'm wondering if we can get a temporary fix for this with a reference to the issue in the code, perhaps with a compiler condition to only do so if we're on next? As I mentioned before, simply commenting out the return fixes the issue.

**Comment by Gama11** [comment] 2016-09-07 19:28
Sure, that's pretty reasonable. Working on it...

**Closed** 2016-09-07 19:31 UTC
Labels: Bug, OpenFL / Lime
