### ISSUE TITLE
FlxRandom.getObject() does not respect startIndex

### ISSUE THREAD

**Issue by Poobslag** [HaxeFlixel/flixel#2009] opened 2016-12-05 02:02 UTC
- **Flixel version:** 4.1.1

FlxRandom.getObject does not respect the startIndex. If you specify a startIndex of 3, for example, FlxRandom.getObject will still return array items with starting indexes below 3.

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.text.FlxText;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var s:String = "";
		for (i in 0...10) {
			s += FlxG.random.getObject(["x", "y", "z", "e", "e"], null, 3, 4);
		}
		add(new FlxText(0, 0, 0, "Have a d" + s + "lightful day"));
	}
}
```

________________________________

**Observed behavior:**
"Have a dxxxyyyyxxxlightful day" is printed, FlxG.random.getObject returns random array items with index [0, 1].

**Expected behavior:**

"Have a deeeeeeeeeelightful day" should be printed. FlxG.random.getObject should return random array items with index [3, 4].

**Comment by Beeblerox** [comment] 2016-12-05 07:11
i guess that the line https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxRandom.hx#L292
`selected = Objects[weightedPick(_arrayFloatHelper)];`
should be changed to 
`selected = Objects[StartIndex + weightedPick(_arrayFloatHelper)];`

**Comment by Beeblerox** [comment] 2016-12-05 10:27
@Poobslag i've commited this change, could you check if the issue is gone?

**Comment by Poobslag** [comment] 2016-12-05 13:13
Yeah, looks like that change fixes the issue. Thanks!

**Comment by Beeblerox** [comment] 2016-12-05 13:24
@Poobslag can we close this issue then?

**Closed** 2016-12-05 13:26 UTC

**Comment by MSGhero** [comment] 2016-12-05 14:47
Unit test 😁
