### ISSUE TITLE
FlxButton loses alignment after scaling

### ISSUE THREAD

**Issue by gcardozo123** [HaxeFlixel/flixel#2089] opened 2017-07-11 00:15 UTC
- **Haxe version:** 3.4.0
- **Flixel version:** 4.2.1
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** Neko, HTML5, Flash, Windows (I didn't test Tizen, Android, WebOS and Blackberry)

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
                var a = new FlxButton(0, 0, "Start Game");
                a.scale.set(2, 2);
                a.screenCenter();
                a.updateHitbox(); 
                a.y += 60;
                add(a);
	}
}
```

________________________________

**Observed behavior:**
Either the text goes to wrong position, or its frame. And the button is not on the screen center anymore.
![untitled2](https://user-images.githubusercontent.com/9798466/28045452-8a2e7b1a-65b3-11e7-8943-b855fd94919f.png)

If you comment the `a.updateHitbox();` line, the button looks fine, but (of course) the mouse over won't behave as expected.
![untitled1](https://user-images.githubusercontent.com/9798466/28045455-8f07f7ce-65b3-11e7-9055-18dfb70c05b9.png)

**Comment by gcardozo123** [comment] 2017-07-11 00:59
Looks like the text is moving when updating the offset.
If you comment the line `offset.set...` in FlxSprite.updateHitbox, the text stays on the correct position.

```haxe
public function updateHitbox():Void
{
	width = Math.abs(scale.x) * frameWidth;
	height = Math.abs(scale.y) * frameHeight;
	//offset.set(-0.5 * (width - frameWidth), -0.5 * (height - frameHeight));
	centerOrigin();
}
```
![untitled3](https://user-images.githubusercontent.com/9798466/28046576-f9148a9a-65ba-11e7-93b6-be27e367c973.png)

**Comment by gcardozo123** [comment] 2017-07-11 02:18
Apparently it's not the text that is moved, but the button background itself. 
If you `trace(a.getPosition());` before and after `a.updateHitbox();` both traces show the same position, so I guess the frame is only moving internally (on its own container). Look:
**Without a.updateHitbox();**
![untitled2](https://user-images.githubusercontent.com/9798466/28048213-d8142b2e-65c5-11e7-8449-ca96bda19f83.png)

**With a.updateHitbox();**
![untitled1](https://user-images.githubusercontent.com/9798466/28048240-fe9321ce-65c5-11e7-9923-925cb4765add.png)

**Comment by DleanJeans** [comment] 2017-07-11 07:42
This is a workaround I got
```
        var button = new FlxButton(0, 0, "Start Game");
        button.scale.set(2, 2);
        button.updateHitbox();
        button.label.fieldWidth = button.width;
        button.label.alignment = "center";
        button.label.offset.y -= 10;
        button.screenCenter();
        add(button);
```

The hitbox of the text is off but it doesn't matter

![button](https://user-images.githubusercontent.com/12462089/28056388-022b3674-6647-11e7-86a2-c1d399b856fe.png)

**Comment by Gama11** [comment] 2017-07-11 08:38
Seems like a duplicate of https://github.com/HaxeFlixel/flixel/issues/2047.

**Closed by Gama11** 2017-07-11 08:38 UTC
Labels: Duplicate

**Comment by gcardozo123** [comment] 2017-07-11 11:08
@Gama11 is this a duplicate? Because in #2047 he doesn't seem to use the `updateHitbox` method, unless it's being called internally by one the other statements in #2047.

**Comment by gcardozo123** [comment] 2017-07-11 11:29
Thank you @DleanJeans!

**Comment by Gama11** [comment] 2017-07-11 11:41
Both issues are about button scaling not working as expected.
