### ISSUE TITLE
Trying to move multiple Flx Objects in sync with another causes strange slide effect

### ISSUE THREAD

**Issue by Ashedragon** [HaxeFlixel/flixel#1779] opened 2016-03-17 06:06 UTC
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:**
Neko as far as I'm aware.

I expect to have a few sprites perfectly in sync with one another, but I get sprites sliding all over the place as if they are trying to catch up to the "anchor" sprite.

**Comment by GimmickyApps** [comment] 2016-03-17 06:33
Can you post your sync code, or better yet, a reproducible example?

**Comment by Gama11** [comment] 2016-03-17 08:15
Agreed, that's not a useful issue report.

**Comment by gamedevsam** [comment] 2016-03-17 15:04
If one object depends on the position of another object, than the update order of the objects will matter (if the object "following" the other gets updated first, it could lag a frame behind).

**Comment by Gama11** [comment] 2016-03-17 17:59
Closing until there's some code to repro.

**Closed by Gama11** 2016-03-17 17:59 UTC
Labels: Can't reproduce

**Comment by Ashedragon** [comment] 2016-03-17 19:38
I thought it was obvious enough and code was painfully unnecessary... I'll add some when I get home.

**Comment by Ashedragon** [comment] 2016-03-18 01:43
Okay, uh, it appears this is all just the result of unexpected behavior from FlxTween. It's almost like it updates alongside and independant of the update function of my sprites. That, combined with the fact that I was calculating the position of the sprites each frame, is what lead to the "lagging behind". It was dumb to calculate the position more than once per frame anyways... 

I apologize for taking jabs at you guys' intelligence. Although it's not like it's made obvious how FlxTween behaves anywhere--not that I mean to defend my position at all.

**Comment by MSGhero** [comment] 2016-03-18 02:17
It's on the docket to get changed ... one day :)

**Comment by GimmickyApps** [comment] 2016-03-18 05:04
Ashedragon no worries, I was going to comment, because I've learned from reporting a few issues: that even though something may seem obviously broken and I think anybody who is using the lib would know what I'm talking about, making a reproducible example is really helpful for my own perspective (not to mention the library devs) in a couple ways.  While sometimes painful as you say, I find personally that about half the time, it's actually a problem in my code, and the other half of the time, when it _is_ an issue to report with the library, I at least become acquainted with the nature of the bug to the extent that I know how to work around it for my project.  Once in a while, I can even see the problem in the library at the code level and help fix it.  :)

**Comment by Ashedragon** [comment] 2016-03-18 05:21
Yeah, I was being short-sighted. It seems like a really good idea to try to reproduce it when I think about it, so I'll be doing that more in the future. :3
