### ISSUE TITLE
Animation order wrong when running in Flash

### ISSUE THREAD

**Issue by flabbyfabby** [HaxeFlixel/flixel#1472] opened 2015-04-14 04:13 UTC
I am using a TexturePackerData to load a sprite sheet I made with Texture Packer.

To play the animation I'm using animation.addByPrefix().

When I run the game in Neko and Desktop the animation is fine. When I run it in Flash the animation is not in the correct order.

The image names are named player_jump000.png - player_jump016.png (does the zero before make a difference?).

edit:

I just tried animation.addByIndices("jump", "player_jump/player_jump", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], ".png", 30, false); and this works fine.

**Comment by Beeblerox** [comment] 2015-04-14 06:22
so the issue is with addByPrefix() i guess. i'll try to fix it today/tomorror

**Comment by Beeblerox** [comment] 2015-04-14 06:32
should be fixed on the dev (i think)

**Comment by Beeblerox** [comment] 2015-04-14 06:34
@flabbyfabby what version of flixel do you use?

**Comment by flabbyfabby** [comment] 2015-04-14 08:34
@Beeblerox verson 3.3.8.

**Comment by Beeblerox** [comment] 2015-04-14 10:22
this issue seems to be fixed on the dev branch, but it differs very much from 3.3.8

**Closed** 2015-06-20 09:17 UTC
