### ISSUE TITLE
Semi-transparent colors in sprites turn black on -Dnext

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#2026] opened 2017-01-09 04:24 UTC
- **Flixel version:** dev
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** neko, windows

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.util.FlxColor;

class PlayState extends FlxState {
    var sprite:FlxSprite;
    
    override public function create():Void {
        super.create();
        sprite = new FlxSprite();
        sprite.makeGraphic(300, 300, FlxColor.RED & 0x88FFFFFF);
        add(sprite);
        bgColor = FlxColor.GREEN;
    }
}
```

If I remove the `& 0x88ffffff` part, the sprite is plain red (which is good) on both legacy and next.

________________________________

**Observed behavior:**
(next)
![default](https://cloud.githubusercontent.com/assets/11571820/21757157/9aabd0f8-d63b-11e6-9bfb-ea1b1e3b03cf.png)

**Expected behavior:**
(legacy and Flash)
![default](https://cloud.githubusercontent.com/assets/11571820/21757152/89b9fdb0-d63b-11e6-89a2-864c34b9b393.png)

**Comment by IBwWG** [comment] 2017-02-01 17:25
I'm getting this also on linux64 with haxe 3.4.0, haxeflixel 4.2.0, openfl 3.6.1, lime 2.9.1.

`lime test neko`:

![limewithoutdnext](https://cloud.githubusercontent.com/assets/16719964/22518053/83d0c99c-e8ab-11e6-8485-9e6391633a84.png)

`lime test neko -Dnext`:

![limednext](https://cloud.githubusercontent.com/assets/16719964/22518055/85de001a-e8ab-11e6-945d-f228b5099852.png)

As you can see, the effect is dramatic as soon as you're 1/255th less than full alpha, and gets worse from there.

Code used:

```
package;

import flixel.FlxState;
import flixel.FlxSprite;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		super.create();
		for (i in 0...256) {
			var box = new FlxSprite();
			var colour = new FlxColor(FlxColor.WHITE);
			colour.alpha = 256 - i;
			box.makeGraphic(10, 120, colour);
			box.setPosition(10 * (i % 64), 120 * Std.int(i / 64));
			add(box);
		}
	}
}
```

**Comment by Tembac** [comment] 2017-02-01 19:45
This is maybe a problem with openfl 3.6.1. 

I had a similar problem before using only openfl. It was supposedly fixed october 2015: http://community.openfl.org/t/several-problems-with-swf-from-fla-and-windows-target/6628

**Comment by Gama11** [comment] 2017-02-01 19:47
@Tembac OpenFL 3.6.1 should have that fix then, it was released 2016-03-29.

**Comment by Tembac** [comment] 2017-02-01 20:10
Ups, I have my years mixed :D jaja.

**Comment by Gama11** [comment] 2017-05-21 16:48
@Beeblerox I wanted to see whether this will be fixed by #2068 - it seems the colors of the sprite in the upper left is somewhat off:

<img src="http://i.imgur.com/Vz0dpTA.png" width="50%"/>

vs Flash (expected):

<img src="http://i.imgur.com/vgEqHYj.png" width="50%"/>

**Comment by Beeblerox** [comment] 2017-05-21 17:12
@Gama11 i will look into it.

**Comment by Beeblerox** [comment] 2017-05-21 17:39
@Gama11 i think the problem on my branch is caused by shaders which suppose to work with premultiplied alpha. So in order to fix this i need to add new property to material and chose shader appropriately.

You can check it yourself if you change `DEFAULT_FRAGMENT_SOURCE` constant it `flixel.graphics.shaders.quads.FlxTexturedShader` class to:
```
	public static inline var DEFAULT_FRAGMENT_SOURCE:String = 
			"
			varying vec2 vTexCoord;
			varying vec4 vColor;
			varying vec4 vColorOffset;
			
			uniform sampler2D uImage0;
			
			void main(void) 
			{
				vec4 color = texture2D(uImage0, vTexCoord);
				
				vec4 result = color * vColor + vColorOffset;
				result = clamp(result, 0.0, 1.0);
				
				gl_FragColor = result;
			}";
```

**Comment by Gama11** [comment] 2018-04-19 23:39
This looks good to me with OpenFL 8:

![](https://i.imgur.com/zplbYLc.png)

**Closed by Gama11** 2018-04-19 23:39 UTC
Labels: Bug, OpenFL / Lime, Rendering
